export type ExecutiveMilitaryBaseRegion =
  | 'Africa'
  | 'Arctic'
  | 'Europe'
  | 'Indo-Pacific'
  | 'Middle East'
  | 'Western Hemisphere'

export type ExecutiveMilitaryBaseService =
  | 'Air Force'
  | 'Army'
  | 'Joint'
  | 'Marine Corps'
  | 'Navy'

export interface ExecutiveMilitaryBase {
  country: string
  id: string
  latitude: number
  location: string
  longitude: number
  name: string
  note: string
  region: ExecutiveMilitaryBaseRegion
  service: ExecutiveMilitaryBaseService
  type: string
}

export const EXECUTIVE_MILITARY_BASE_SOURCE_LABEL = 'DoD Base Structure Report'
export const EXECUTIVE_MILITARY_BASE_SOURCE_URL =
  'https://www.acq.osd.mil/eie/imr/rpid/library.html'

export const EXECUTIVE_MILITARY_BASE_REGIONS: ExecutiveMilitaryBaseRegion[] = [
  'Europe',
  'Arctic',
  'Middle East',
  'Africa',
  'Indo-Pacific',
  'Western Hemisphere',
]

export const EXECUTIVE_MILITARY_BASES: ExecutiveMilitaryBase[] = [
  {
    country: 'Germany',
    id: 'ramstein-air-base',
    latitude: 49.4369,
    location: 'Ramstein-Miesenbach',
    longitude: 7.6003,
    name: 'Ramstein Air Base',
    note: 'Major U.S. Air Force airlift and command hub in Europe.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Air base',
  },
  {
    country: 'Germany',
    id: 'spangdahlem-air-base',
    latitude: 49.9727,
    location: 'Spangdahlem',
    longitude: 6.6925,
    name: 'Spangdahlem Air Base',
    note: 'Key fighter and expeditionary aviation site in Germany.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Air base',
  },
  {
    country: 'Germany',
    id: 'wiesbaden-army-garrison',
    latitude: 50.0496,
    location: 'Wiesbaden',
    longitude: 8.3254,
    name: 'U.S. Army Garrison Wiesbaden',
    note: 'Army headquarters and logistics node for Europe-based operations.',
    region: 'Europe',
    service: 'Army',
    type: 'Army garrison',
  },
  {
    country: 'Germany',
    id: 'stuttgart-army-garrison',
    latitude: 48.7517,
    location: 'Stuttgart',
    longitude: 9.1049,
    name: 'U.S. Army Garrison Stuttgart',
    note: 'Hosts major combatant-command headquarters in Europe.',
    region: 'Europe',
    service: 'Army',
    type: 'Army garrison',
  },
  {
    country: 'Germany',
    id: 'grafenwoehr-training-area',
    latitude: 49.6987,
    location: 'Grafenwoehr',
    longitude: 11.938,
    name: 'Grafenwoehr Training Area',
    note: 'Large Army training complex used for multinational exercises.',
    region: 'Europe',
    service: 'Army',
    type: 'Training area',
  },
  {
    country: 'Italy',
    id: 'aviano-air-base',
    latitude: 46.0319,
    location: 'Aviano',
    longitude: 12.5965,
    name: 'Aviano Air Base',
    note: 'Front-line U.S. Air Force fighter base in southern Europe.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Air base',
  },
  {
    country: 'Italy',
    id: 'nas-sigonella',
    latitude: 37.4019,
    location: 'Sigonella, Sicily',
    longitude: 14.9228,
    name: 'Naval Air Station Sigonella',
    note: 'Mediterranean logistics, patrol, and aviation hub.',
    region: 'Europe',
    service: 'Navy',
    type: 'Naval air station',
  },
  {
    country: 'Italy',
    id: 'nsa-naples',
    latitude: 40.8229,
    location: 'Naples',
    longitude: 14.0917,
    name: 'Naval Support Activity Naples',
    note: 'Supports U.S. Sixth Fleet and NATO-linked maritime operations.',
    region: 'Europe',
    service: 'Navy',
    type: 'Naval support activity',
  },
  {
    country: 'Italy',
    id: 'camp-darby',
    latitude: 43.6279,
    location: 'Pisa-Livorno',
    longitude: 10.2939,
    name: 'Camp Darby',
    note: 'Army logistics and ammunition hub between Pisa and Livorno.',
    region: 'Europe',
    service: 'Army',
    type: 'Logistics site',
  },
  {
    country: 'Spain',
    id: 'naval-station-rota',
    latitude: 36.6408,
    location: 'Rota',
    longitude: -6.3494,
    name: 'Naval Station Rota',
    note: 'Strategic Atlantic-Mediterranean naval gateway and destroyer port.',
    region: 'Europe',
    service: 'Navy',
    type: 'Naval station',
  },
  {
    country: 'Spain',
    id: 'moron-air-base',
    latitude: 37.1749,
    location: 'Moron de la Frontera',
    longitude: -5.6159,
    name: 'Moron Air Base',
    note: 'Supports rapid-response and air mobility missions.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Air base',
  },
  {
    country: 'United Kingdom',
    id: 'raf-lakenheath',
    latitude: 52.4097,
    location: 'Lakenheath',
    longitude: 0.5608,
    name: 'RAF Lakenheath',
    note: 'Principal U.S. fighter base in the United Kingdom.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Air base',
  },
  {
    country: 'United Kingdom',
    id: 'raf-mildenhall',
    latitude: 52.3617,
    location: 'Mildenhall',
    longitude: 0.4864,
    name: 'RAF Mildenhall',
    note: 'Supports tanker, special operations, and global airlift missions.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Air base',
  },
  {
    country: 'United Kingdom',
    id: 'raf-croughton',
    latitude: 51.9977,
    location: 'Croughton',
    longitude: -1.1704,
    name: 'RAF Croughton',
    note: 'Communications and intelligence support site.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Communications station',
  },
  {
    country: 'Turkey',
    id: 'incirlik-air-base',
    latitude: 37.0021,
    location: 'Adana',
    longitude: 35.4259,
    name: 'Incirlik Air Base',
    note: 'Long-standing NATO-linked U.S. air operations platform.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Air base',
  },
  {
    country: 'Greece',
    id: 'nsa-souda-bay',
    latitude: 35.5317,
    location: 'Crete',
    longitude: 24.1497,
    name: 'NSA Souda Bay',
    note: 'Eastern Mediterranean naval and air support location.',
    region: 'Europe',
    service: 'Navy',
    type: 'Naval support activity',
  },
  {
    country: 'Kosovo',
    id: 'camp-bondsteel',
    latitude: 42.3864,
    location: 'Ferizaj area',
    longitude: 21.3727,
    name: 'Camp Bondsteel',
    note: 'Major U.S. Army presence tied to KFOR operations.',
    region: 'Europe',
    service: 'Army',
    type: 'Army camp',
  },
  {
    country: 'Greenland',
    id: 'pituffik-space-base',
    latitude: 76.5312,
    location: 'Pituffik',
    longitude: -68.7032,
    name: 'Pituffik Space Base',
    note: 'Arctic missile-warning and space-surveillance site.',
    region: 'Arctic',
    service: 'Air Force',
    type: 'Space base',
  },
  {
    country: 'Djibouti',
    id: 'camp-lemonnier',
    latitude: 11.5466,
    location: 'Djibouti City',
    longitude: 43.1595,
    name: 'Camp Lemonnier',
    note: 'Primary enduring U.S. military hub in the Horn of Africa.',
    region: 'Africa',
    service: 'Joint',
    type: 'Joint base',
  },
  {
    country: 'Bahrain',
    id: 'nsa-bahrain',
    latitude: 26.2285,
    location: 'Manama',
    longitude: 50.586,
    name: 'Naval Support Activity Bahrain',
    note: 'Home port area for Fifth Fleet operations in the Gulf.',
    region: 'Middle East',
    service: 'Navy',
    type: 'Naval support activity',
  },
  {
    country: 'Qatar',
    id: 'al-udeid-air-base',
    latitude: 25.1173,
    location: 'Near Doha',
    longitude: 51.3144,
    name: 'Al Udeid Air Base',
    note: 'Major Combined Air Operations and logistics hub in the region.',
    region: 'Middle East',
    service: 'Air Force',
    type: 'Air base',
  },
  {
    country: 'United Arab Emirates',
    id: 'al-dhafra-air-base',
    latitude: 24.2486,
    location: 'Abu Dhabi area',
    longitude: 54.5477,
    name: 'Al Dhafra Air Base',
    note: 'Regional airpower and intelligence platform.',
    region: 'Middle East',
    service: 'Air Force',
    type: 'Air base',
  },
  {
    country: 'Jordan',
    id: 'muwaffaq-salti-air-base',
    latitude: 32.0295,
    location: 'Azraq',
    longitude: 36.146,
    name: 'Muwaffaq Salti Air Base',
    note: 'Jointly used regional air operations site.',
    region: 'Middle East',
    service: 'Air Force',
    type: 'Air base',
  },
  {
    country: 'Kuwait',
    id: 'camp-arifjan',
    latitude: 28.847,
    location: 'Near Kuwait City',
    longitude: 48.2676,
    name: 'Camp Arifjan',
    note: 'Army logistics and command hub for Southwest Asia.',
    region: 'Middle East',
    service: 'Army',
    type: 'Army camp',
  },
  {
    country: 'Kuwait',
    id: 'camp-buehring',
    latitude: 29.6305,
    location: 'Northwestern Kuwait',
    longitude: 47.9301,
    name: 'Camp Buehring',
    note: 'Army staging and training site supporting regional movements.',
    region: 'Middle East',
    service: 'Army',
    type: 'Army camp',
  },
  {
    country: 'Kuwait',
    id: 'ali-al-salem-air-base',
    latitude: 29.3467,
    location: 'Ali Al Salem',
    longitude: 47.5207,
    name: 'Ali Al Salem Air Base',
    note: 'Air mobility and expeditionary support location.',
    region: 'Middle East',
    service: 'Air Force',
    type: 'Air base',
  },
  {
    country: 'Saudi Arabia',
    id: 'prince-sultan-air-base',
    latitude: 24.0628,
    location: 'Al Kharj',
    longitude: 47.5806,
    name: 'Prince Sultan Air Base',
    note: 'Regional air-defense and air-operations site.',
    region: 'Middle East',
    service: 'Air Force',
    type: 'Air base',
  },
  {
    country: 'Japan',
    id: 'yokosuka-naval-base',
    latitude: 35.281,
    location: 'Yokosuka',
    longitude: 139.667,
    name: 'Yokosuka Naval Base',
    note: 'Forward-deployed naval headquarters and carrier homeport.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Naval base',
  },
  {
    country: 'Japan',
    id: 'yokota-air-base',
    latitude: 35.7485,
    location: 'Tokyo area',
    longitude: 139.3485,
    name: 'Yokota Air Base',
    note: 'Major airlift and command center in Japan.',
    region: 'Indo-Pacific',
    service: 'Air Force',
    type: 'Air base',
  },
  {
    country: 'Japan',
    id: 'kadena-air-base',
    latitude: 26.3556,
    location: 'Okinawa',
    longitude: 127.7677,
    name: 'Kadena Air Base',
    note: 'Largest U.S. Air Force installation in the Indo-Pacific.',
    region: 'Indo-Pacific',
    service: 'Air Force',
    type: 'Air base',
  },
  {
    country: 'Japan',
    id: 'camp-butler',
    latitude: 26.3344,
    location: 'Okinawa',
    longitude: 127.8056,
    name: 'Camp Butler',
    note: 'Marine Corps network of camps and support facilities on Okinawa.',
    region: 'Indo-Pacific',
    service: 'Marine Corps',
    type: 'Marine Corps base',
  },
  {
    country: 'Japan',
    id: 'mcas-iwakuni',
    latitude: 34.1513,
    location: 'Iwakuni',
    longitude: 132.2356,
    name: 'MCAS Iwakuni',
    note: 'Major Marine Corps aviation base in western Japan.',
    region: 'Indo-Pacific',
    service: 'Marine Corps',
    type: 'Marine Corps air station',
  },
  {
    country: 'Japan',
    id: 'misawa-air-base',
    latitude: 40.7032,
    location: 'Misawa',
    longitude: 141.3688,
    name: 'Misawa Air Base',
    note: 'Air Force and joint surveillance site in northern Japan.',
    region: 'Indo-Pacific',
    service: 'Air Force',
    type: 'Air base',
  },
  {
    country: 'Japan',
    id: 'fleet-activities-sasebo',
    latitude: 33.159,
    location: 'Sasebo',
    longitude: 129.7167,
    name: 'Fleet Activities Sasebo',
    note: 'Forward naval logistics and amphibious support port.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Fleet activities site',
  },
  {
    country: 'Japan',
    id: 'camp-zama',
    latitude: 35.4882,
    location: 'Kanagawa',
    longitude: 139.3937,
    name: 'Camp Zama',
    note: 'Army command and support installation near Tokyo.',
    region: 'Indo-Pacific',
    service: 'Army',
    type: 'Army garrison',
  },
  {
    country: 'South Korea',
    id: 'camp-humphreys',
    latitude: 36.9665,
    location: 'Pyeongtaek',
    longitude: 127.0301,
    name: 'Camp Humphreys',
    note: 'Largest U.S. overseas military installation by area.',
    region: 'Indo-Pacific',
    service: 'Army',
    type: 'Army garrison',
  },
  {
    country: 'South Korea',
    id: 'osan-air-base',
    latitude: 37.0907,
    location: 'Pyeongtaek',
    longitude: 127.0298,
    name: 'Osan Air Base',
    note: 'Key U.S. Air Force air-defense and readiness base on the peninsula.',
    region: 'Indo-Pacific',
    service: 'Air Force',
    type: 'Air base',
  },
  {
    country: 'Guam',
    id: 'andersen-air-force-base',
    latitude: 13.584,
    location: 'Yigo',
    longitude: 144.9307,
    name: 'Andersen Air Force Base',
    note: 'Strategic bomber and airlift platform in the western Pacific.',
    region: 'Indo-Pacific',
    service: 'Air Force',
    type: 'Air force base',
  },
  {
    country: 'Guam',
    id: 'naval-base-guam',
    latitude: 13.4443,
    location: 'Santa Rita',
    longitude: 144.6513,
    name: 'Naval Base Guam',
    note: 'Submarine and fleet logistics hub in the Marianas.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Naval base',
  },
  {
    country: 'British Indian Ocean Territory',
    id: 'diego-garcia',
    latitude: -7.3133,
    location: 'Diego Garcia',
    longitude: 72.4111,
    name: 'Naval Support Facility Diego Garcia',
    note: 'Remote logistics and long-range operations hub in the Indian Ocean.',
    region: 'Indo-Pacific',
    service: 'Joint',
    type: 'Support facility',
  },
  {
    country: 'Cuba',
    id: 'guantanamo-bay',
    latitude: 19.9065,
    location: 'Guantanamo Bay',
    longitude: -75.1588,
    name: 'Naval Station Guantanamo Bay',
    note: 'Long-running naval installation in the Caribbean.',
    region: 'Western Hemisphere',
    service: 'Navy',
    type: 'Naval station',
  },
  {
    country: 'Honduras',
    id: 'soto-cano-air-base',
    latitude: 14.3824,
    location: 'Comayagua',
    longitude: -87.6211,
    name: 'Soto Cano Air Base',
    note: 'Joint task-force location for Central America missions.',
    region: 'Western Hemisphere',
    service: 'Joint',
    type: 'Air base',
  },
  {
    country: 'Germany',
    id: 'usag-kaiserslautern',
    latitude: 49.4447,
    location: 'Kaiserslautern',
    longitude: 7.7689,
    name: 'U.S. Army Garrison Kaiserslautern',
    note: 'Large Army garrison footprint within the Kaiserslautern Military Community.',
    region: 'Europe',
    service: 'Army',
    type: 'Army garrison',
  },
  {
    country: 'Germany',
    id: 'landstuhl-regional-medical-center',
    latitude: 49.4131,
    location: 'Landstuhl',
    longitude: 7.5716,
    name: 'Landstuhl Regional Medical Center',
    note: 'Flagship overseas U.S. military hospital and medical evacuation hub in Europe.',
    region: 'Europe',
    service: 'Army',
    type: 'Military medical center',
  },
  {
    country: 'Germany',
    id: 'baumholder-military-community',
    latitude: 49.6178,
    location: 'Baumholder',
    longitude: 7.3401,
    name: 'Baumholder Military Community',
    note: 'Army maneuver and sustainment site tied to the Rheinland-Pfalz network.',
    region: 'Europe',
    service: 'Army',
    type: 'Army military community',
  },
  {
    country: 'Germany',
    id: 'usag-ansbach',
    latitude: 49.3078,
    location: 'Ansbach',
    longitude: 10.5719,
    name: 'U.S. Army Garrison Ansbach',
    note: 'Army garrison in Franconia supporting aviation and sustainment units.',
    region: 'Europe',
    service: 'Army',
    type: 'Army garrison',
  },
  {
    country: 'Germany',
    id: 'rose-barracks-vilseck',
    latitude: 49.6134,
    location: 'Vilseck',
    longitude: 11.8038,
    name: 'Rose Barracks Vilseck',
    note: 'Major U.S. Army installation paired with the Grafenwoehr training footprint.',
    region: 'Europe',
    service: 'Army',
    type: 'Army barracks',
  },
  {
    country: 'Germany',
    id: 'hohenfels-training-area',
    latitude: 49.2181,
    location: 'Hohenfels',
    longitude: 11.8438,
    name: 'Hohenfels Training Area',
    note: 'Multinational combat training center within the Bavaria garrison network.',
    region: 'Europe',
    service: 'Army',
    type: 'Training area',
  },
  {
    country: 'Italy',
    id: 'caserma-ederle',
    latitude: 45.5455,
    location: 'Vicenza',
    longitude: 11.5474,
    name: 'Caserma Ederle',
    note: 'Core Army installation in Vicenza supporting airborne and headquarters units.',
    region: 'Europe',
    service: 'Army',
    type: 'Army installation',
  },
  {
    country: 'Italy',
    id: 'caserma-del-din',
    latitude: 45.5586,
    location: 'Vicenza',
    longitude: 11.5406,
    name: 'Caserma Del Din',
    note: 'Modern Army site in Vicenza used by airborne and support formations.',
    region: 'Europe',
    service: 'Army',
    type: 'Army installation',
  },
  {
    country: 'Italy',
    id: 'nsa-gaeta',
    latitude: 41.2144,
    location: 'Gaeta',
    longitude: 13.5708,
    name: 'Naval Support Activity Gaeta',
    note: 'Mediterranean fleet logistics and support site on the Italian coast.',
    region: 'Europe',
    service: 'Navy',
    type: 'Naval support activity',
  },
  {
    country: 'United Kingdom',
    id: 'raf-fairford',
    latitude: 51.6822,
    location: 'Fairford',
    longitude: -1.7901,
    name: 'RAF Fairford',
    note: 'U.S. Air Force forward operating location for bomber and mobility missions.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Air base',
  },
  {
    country: 'United Kingdom',
    id: 'raf-alconbury',
    latitude: 52.3733,
    location: 'Alconbury',
    longitude: -0.2617,
    name: 'RAF Alconbury',
    note: 'U.S. Air Force support and intelligence-linked installation in eastern England.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Air base',
  },
  {
    country: 'United Kingdom',
    id: 'raf-molesworth',
    latitude: 52.3748,
    location: 'Molesworth',
    longitude: -0.4255,
    name: 'RAF Molesworth',
    note: 'Long-running U.S. defense site tied to intelligence and support missions.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Air station',
  },
  {
    country: 'United Kingdom',
    id: 'raf-menwith-hill',
    latitude: 54.0117,
    location: 'Harrogate area',
    longitude: -1.6822,
    name: 'RAF Menwith Hill',
    note: 'Large U.S.-run signals and intelligence site in the United Kingdom.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Communications station',
  },
  {
    country: 'Portugal',
    id: 'lajes-field',
    latitude: 38.7618,
    location: 'Terceira, Azores',
    longitude: -27.0908,
    name: 'Lajes Field',
    note: 'Atlantic airfield supporting transatlantic logistics and contingency use.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Air base',
  },
  {
    country: 'Romania',
    id: 'mihail-kogalniceanu-air-base',
    latitude: 44.3622,
    location: 'Constanta area',
    longitude: 28.4883,
    name: 'Mihail Kogalniceanu Air Base',
    note: 'Major Black Sea-area hub used by U.S. rotational and transit forces.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Air base',
  },
  {
    country: 'Bulgaria',
    id: 'novo-selo-training-area',
    latitude: 42.6217,
    location: 'Sliven area',
    longitude: 26.7628,
    name: 'Novo Selo Training Area',
    note: 'Training site used for U.S. rotational presence and allied exercises.',
    region: 'Europe',
    service: 'Army',
    type: 'Training area',
  },
  {
    country: 'Poland',
    id: 'camp-kosciuszko',
    latitude: 52.4064,
    location: 'Poznan',
    longitude: 16.9252,
    name: 'Camp Kosciuszko',
    note: 'Named garrison hub for the enduring U.S. Army presence in Poland.',
    region: 'Europe',
    service: 'Army',
    type: 'Army camp',
  },
  {
    country: 'Kuwait',
    id: 'camp-patriot',
    latitude: 29.3569,
    location: 'Kuwait City area',
    longitude: 47.9157,
    name: 'Camp Patriot',
    note: 'Kuwait-based support location linked to regional sustainment and force protection.',
    region: 'Middle East',
    service: 'Army',
    type: 'Army camp',
  },
  {
    country: 'Qatar',
    id: 'camp-as-sayliyah',
    latitude: 25.1888,
    location: 'Doha area',
    longitude: 51.2875,
    name: 'Camp As Sayliyah',
    note: 'Long-used U.S. logistics and prepositioning site outside Doha.',
    region: 'Middle East',
    service: 'Army',
    type: 'Army camp',
  },
  {
    country: 'Saudi Arabia',
    id: 'eskan-village',
    latitude: 24.6827,
    location: 'Riyadh',
    longitude: 46.6879,
    name: 'Eskan Village',
    note: 'Support compound historically used for U.S. military and advisory personnel.',
    region: 'Middle East',
    service: 'Air Force',
    type: 'Support compound',
  },
  {
    country: 'Bahrain',
    id: 'isa-air-base',
    latitude: 25.9184,
    location: 'Southern Governorate',
    longitude: 50.5906,
    name: 'Isa Air Base',
    note: 'Regional airfield used for U.S. and allied military operations.',
    region: 'Middle East',
    service: 'Air Force',
    type: 'Air base',
  },
  {
    country: 'Kenya',
    id: 'camp-simba',
    latitude: -2.2538,
    location: 'Manda Bay',
    longitude: 40.9131,
    name: 'Camp Simba',
    note: 'U.S. military site on the Kenyan coast supporting East Africa missions.',
    region: 'Africa',
    service: 'Joint',
    type: 'Camp',
  },
  {
    country: 'Japan',
    id: 'mcas-futenma',
    latitude: 26.2744,
    location: 'Ginowan, Okinawa',
    longitude: 127.7561,
    name: 'MCAS Futenma',
    note: 'Marine Corps aviation base in Okinawa with rotary-wing and support missions.',
    region: 'Indo-Pacific',
    service: 'Marine Corps',
    type: 'Marine Corps air station',
  },
  {
    country: 'Japan',
    id: 'camp-foster',
    latitude: 26.3127,
    location: 'Okinawa',
    longitude: 127.761,
    name: 'Camp Foster',
    note: 'Marine Corps installation hosting major command and support functions in Okinawa.',
    region: 'Indo-Pacific',
    service: 'Marine Corps',
    type: 'Marine Corps base',
  },
  {
    country: 'Japan',
    id: 'camp-hansen',
    latitude: 26.4522,
    location: 'Kin, Okinawa',
    longitude: 127.9301,
    name: 'Camp Hansen',
    note: 'Marine Corps training and maneuver area in northern Okinawa.',
    region: 'Indo-Pacific',
    service: 'Marine Corps',
    type: 'Marine Corps base',
  },
  {
    country: 'Japan',
    id: 'camp-schwab',
    latitude: 26.5328,
    location: 'Nago, Okinawa',
    longitude: 128.0401,
    name: 'Camp Schwab',
    note: 'Marine Corps coastal base in northern Okinawa.',
    region: 'Indo-Pacific',
    service: 'Marine Corps',
    type: 'Marine Corps base',
  },
  {
    country: 'Japan',
    id: 'camp-courtney',
    latitude: 26.3794,
    location: 'Uruma, Okinawa',
    longitude: 127.8482,
    name: 'Camp Courtney',
    note: 'Marine Corps installation with headquarters and community support functions.',
    region: 'Indo-Pacific',
    service: 'Marine Corps',
    type: 'Marine Corps base',
  },
  {
    country: 'Japan',
    id: 'camp-kinser',
    latitude: 26.2608,
    location: 'Urasoe, Okinawa',
    longitude: 127.7048,
    name: 'Camp Kinser',
    note: 'Marine Corps logistics hub near Naha and central Okinawa ports.',
    region: 'Indo-Pacific',
    service: 'Marine Corps',
    type: 'Marine Corps base',
  },
  {
    country: 'Japan',
    id: 'white-beach-naval-facility',
    latitude: 26.3071,
    location: 'Uruma, Okinawa',
    longitude: 127.9714,
    name: 'White Beach Naval Facility',
    note: 'Naval support site in Okinawa used for fleet logistics and pier access.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Naval facility',
  },
  {
    country: 'Japan',
    id: 'naf-atsugi',
    latitude: 35.454,
    location: 'Ayase-Yamato',
    longitude: 139.4497,
    name: 'Naval Air Facility Atsugi',
    note: 'Naval aviation and support installation near Tokyo.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Naval air facility',
  },
  {
    country: 'Japan',
    id: 'camp-fuji',
    latitude: 35.2769,
    location: 'Gotemba',
    longitude: 138.8616,
    name: 'Camp Fuji',
    note: 'Marine Corps training site at the base of Mount Fuji.',
    region: 'Indo-Pacific',
    service: 'Marine Corps',
    type: 'Training camp',
  },
  {
    country: 'Japan',
    id: 'torii-station',
    latitude: 26.3895,
    location: 'Yomitan, Okinawa',
    longitude: 127.7447,
    name: 'Torii Station',
    note: 'Army site in Okinawa supporting communications, logistics, and tenant units.',
    region: 'Indo-Pacific',
    service: 'Army',
    type: 'Army station',
  },
  {
    country: 'South Korea',
    id: 'kunsan-air-base',
    latitude: 35.9038,
    location: 'Gunsan',
    longitude: 126.6159,
    name: 'Kunsan Air Base',
    note: 'Key fighter base on the Korean Peninsula.',
    region: 'Indo-Pacific',
    service: 'Air Force',
    type: 'Air base',
  },
  {
    country: 'South Korea',
    id: 'camp-casey',
    latitude: 37.9194,
    location: 'Dongducheon',
    longitude: 127.0732,
    name: 'Camp Casey',
    note: 'Forward Army installation north of Seoul with long-standing deterrence mission.',
    region: 'Indo-Pacific',
    service: 'Army',
    type: 'Army camp',
  },
  {
    country: 'South Korea',
    id: 'camp-stanley',
    latitude: 37.7171,
    location: 'Uijeongbu',
    longitude: 127.0719,
    name: 'Camp Stanley',
    note: 'Named Army site in the Seoul-area U.S. force posture.',
    region: 'Indo-Pacific',
    service: 'Army',
    type: 'Army camp',
  },
  {
    country: 'South Korea',
    id: 'camp-walker',
    latitude: 35.8534,
    location: 'Daegu',
    longitude: 128.6081,
    name: 'Camp Walker',
    note: 'Principal U.S. Army installation in Daegu.',
    region: 'Indo-Pacific',
    service: 'Army',
    type: 'Army camp',
  },
  {
    country: 'South Korea',
    id: 'camp-henry',
    latitude: 35.871,
    location: 'Daegu',
    longitude: 128.5913,
    name: 'Camp Henry',
    note: 'Army installation in central Daegu tied to command and support functions.',
    region: 'Indo-Pacific',
    service: 'Army',
    type: 'Army camp',
  },
  {
    country: 'South Korea',
    id: 'camp-carroll',
    latitude: 35.9819,
    location: 'Waegwan',
    longitude: 128.3893,
    name: 'Camp Carroll',
    note: 'Army logistics and sustainment site in southeastern Korea.',
    region: 'Indo-Pacific',
    service: 'Army',
    type: 'Army camp',
  },
  {
    country: 'South Korea',
    id: 'chinhae-naval-base',
    latitude: 35.1046,
    location: 'Jinhae',
    longitude: 128.6572,
    name: 'Chinhae Naval Base',
    note: 'Naval support point used by U.S. forces on Korea’s southern coast.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Naval base',
  },
  {
    country: 'South Korea',
    id: 'camp-bonifas',
    latitude: 37.9233,
    location: 'DMZ area',
    longitude: 126.7099,
    name: 'Camp Bonifas',
    note: 'Army post associated with the Joint Security Area mission near the DMZ.',
    region: 'Indo-Pacific',
    service: 'Army',
    type: 'Army camp',
  },
  {
    country: 'Guam',
    id: 'camp-blaz',
    latitude: 13.5516,
    location: 'Dededo',
    longitude: 144.8397,
    name: 'Marine Corps Base Camp Blaz',
    note: 'Newest major Marine Corps base in the western Pacific.',
    region: 'Indo-Pacific',
    service: 'Marine Corps',
    type: 'Marine Corps base',
  },
  {
    country: 'Marshall Islands',
    id: 'kwajalein-test-site',
    latitude: 8.725,
    location: 'Kwajalein Atoll',
    longitude: 167.731,
    name: 'Ronald Reagan Ballistic Missile Defense Test Site',
    note: 'Strategic missile test and space-tracking range in the central Pacific.',
    region: 'Indo-Pacific',
    service: 'Army',
    type: 'Test site',
  },
  {
    country: 'Singapore',
    id: 'changi-naval-base',
    latitude: 1.3784,
    location: 'Changi',
    longitude: 104.0262,
    name: 'Changi Naval Base',
    note: 'Regional logistics and port access point used by U.S. Navy ships.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Naval base',
  },
  {
    country: 'Singapore',
    id: 'sembawang-wharves',
    latitude: 1.462,
    location: 'Sembawang',
    longitude: 103.817,
    name: 'Sembawang Wharves',
    note: 'Support location for U.S. naval logistics and visiting ships in Singapore.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Naval logistics site',
  },
  {
    country: 'Australia',
    id: 'pine-gap',
    latitude: -23.7991,
    location: 'Near Alice Springs',
    longitude: 133.7375,
    name: 'Joint Defence Facility Pine Gap',
    note: 'Joint U.S.-Australian strategic surveillance and intelligence site.',
    region: 'Indo-Pacific',
    service: 'Joint',
    type: 'Joint facility',
  },
  {
    country: 'Wake Island',
    id: 'wake-island-airfield',
    latitude: 19.2821,
    location: 'Wake Atoll',
    longitude: 166.636,
    name: 'Wake Island Airfield',
    note: 'Remote U.S. Pacific airfield and support installation.',
    region: 'Indo-Pacific',
    service: 'Air Force',
    type: 'Airfield',
  },
  {
    country: 'El Salvador',
    id: 'csl-comalapa',
    latitude: 13.4407,
    location: 'Comalapa',
    longitude: -89.0557,
    name: 'Cooperative Security Location Comalapa',
    note: 'U.S. forward site in El Salvador used for regional air and maritime missions.',
    region: 'Western Hemisphere',
    service: 'Joint',
    type: 'Cooperative security location',
  },
  {
    country: 'Curacao',
    id: 'csl-hato-curacao',
    latitude: 12.1889,
    location: 'Hato',
    longitude: -68.9598,
    name: 'Cooperative Security Location Hato',
    note: 'Forward operating location in Curacao for regional surveillance missions.',
    region: 'Western Hemisphere',
    service: 'Joint',
    type: 'Cooperative security location',
  },
  {
    country: 'Aruba',
    id: 'csl-reina-beatrix',
    latitude: 12.5014,
    location: 'Oranjestad',
    longitude: -70.0152,
    name: 'Cooperative Security Location Reina Beatrix',
    note: 'Aruba airfield used for regional U.S. counter-narcotics and surveillance missions.',
    region: 'Western Hemisphere',
    service: 'Joint',
    type: 'Cooperative security location',
  },
  {
    country: 'Puerto Rico',
    id: 'fort-buchanan',
    latitude: 18.4038,
    location: 'Guaynabo-San Juan',
    longitude: -66.1014,
    name: 'Fort Buchanan',
    note: 'Major Army installation in Puerto Rico and a key Caribbean support hub.',
    region: 'Western Hemisphere',
    service: 'Army',
    type: 'Army fort',
  },
  {
    country: 'Bahamas',
    id: 'autec-andros',
    latitude: 24.6939,
    location: 'Andros Island',
    longitude: -77.7964,
    name: 'AUTEC Andros',
    note: 'U.S. Navy undersea test and evaluation range in the Bahamas.',
    region: 'Western Hemisphere',
    service: 'Navy',
    type: 'Undersea test range',
  },
  {
    country: 'Puerto Rico',
    id: 'camp-santiago',
    latitude: 18.0061,
    location: 'Salinas',
    longitude: -66.3073,
    name: 'Camp Santiago',
    note: 'National Guard training installation with regular U.S. military exercise use.',
    region: 'Western Hemisphere',
    service: 'Army',
    type: 'Training camp',
  },
  {
    country: 'Belgium',
    id: 'chievres-air-base',
    latitude: 50.5758,
    location: 'Chièvres',
    longitude: 3.8313,
    name: 'Chièvres Air Base',
    note: 'Main U.S. Army Benelux airfield and logistics point in Belgium.',
    region: 'Europe',
    service: 'Army',
    type: 'Air base',
  },
  {
    country: 'Poland',
    id: 'powidz-aps-site',
    latitude: 52.3792,
    location: 'Powidz',
    longitude: 17.8533,
    name: 'Powidz APS Site',
    note: 'Army prepositioned stocks and logistics site supporting NATO’s eastern flank.',
    region: 'Europe',
    service: 'Army',
    type: 'Army logistics site',
  },
  {
    country: 'Poland',
    id: 'redzikowo-aegis-ashore',
    latitude: 54.5817,
    location: 'Redzikowo',
    longitude: 17.1095,
    name: 'Aegis Ashore Redzikowo',
    note: 'U.S. missile-defense installation on Poland’s Baltic coast.',
    region: 'Europe',
    service: 'Navy',
    type: 'Missile-defense site',
  },
  {
    country: 'Romania',
    id: 'deveselu-aegis-ashore',
    latitude: 44.0622,
    location: 'Deveselu',
    longitude: 24.381,
    name: 'Aegis Ashore Deveselu',
    note: 'U.S. ballistic missile-defense site in southern Romania.',
    region: 'Europe',
    service: 'Navy',
    type: 'Missile-defense site',
  },
  {
    country: 'Iraq',
    id: 'ain-al-asad-air-base',
    latitude: 33.7856,
    location: 'Al Anbar',
    longitude: 42.4412,
    name: 'Ain al-Asad Air Base',
    note: 'Large western Iraq air base used by U.S. forces for regional operations.',
    region: 'Middle East',
    service: 'Joint',
    type: 'Air base',
  },
  {
    country: 'Iraq',
    id: 'erbil-air-base',
    latitude: 36.2376,
    location: 'Erbil',
    longitude: 43.9632,
    name: 'Erbil Air Base',
    note: 'Northern Iraq air hub tied to U.S. advisory and regional support missions.',
    region: 'Middle East',
    service: 'Joint',
    type: 'Air base',
  },
  {
    country: 'Djibouti',
    id: 'chabelley-airfield',
    latitude: 11.5474,
    location: 'Chabelley',
    longitude: 43.2547,
    name: 'Chabelley Airfield',
    note: 'Outlying Djibouti airfield used for U.S. unmanned and support operations.',
    region: 'Africa',
    service: 'Joint',
    type: 'Airfield',
  },
  {
    country: 'Japan',
    id: 'sagami-general-depot',
    latitude: 35.5738,
    location: 'Sagamihara',
    longitude: 139.3732,
    name: 'Sagami General Depot',
    note: 'Army logistics and sustainment site in the Tokyo area.',
    region: 'Indo-Pacific',
    service: 'Army',
    type: 'Army depot',
  },
  {
    country: 'Japan',
    id: 'yokohama-north-dock',
    latitude: 35.4754,
    location: 'Yokohama',
    longitude: 139.6466,
    name: 'Yokohama North Dock',
    note: 'Army and logistics port facility in Yokohama Bay.',
    region: 'Indo-Pacific',
    service: 'Army',
    type: 'Port facility',
  },
  {
    country: 'South Korea',
    id: 'k16-air-base',
    latitude: 37.5181,
    location: 'Seoul',
    longitude: 127.1182,
    name: 'K-16 Air Base',
    note: 'Army aviation and joint-use airfield in the Seoul metropolitan area.',
    region: 'Indo-Pacific',
    service: 'Army',
    type: 'Air base',
  },
  {
    country: 'Hawaii',
    id: 'joint-base-pearl-harbor-hickam',
    latitude: 21.351,
    location: 'Oahu',
    longitude: -157.95,
    name: 'Joint Base Pearl Harbor-Hickam',
    note: 'Flagship Indo-Pacific naval and air hub in Hawaii.',
    region: 'Indo-Pacific',
    service: 'Joint',
    type: 'Joint base',
  },
  {
    country: 'Hawaii',
    id: 'schofield-barracks',
    latitude: 21.4995,
    location: 'Oahu',
    longitude: -158.0476,
    name: 'Schofield Barracks',
    note: 'Major Army post in Hawaii central to Indo-Pacific land-force posture.',
    region: 'Indo-Pacific',
    service: 'Army',
    type: 'Army barracks',
  },
  {
    country: 'Hawaii',
    id: 'marine-corps-base-hawaii',
    latitude: 21.4433,
    location: 'Kaneohe Bay, Oahu',
    longitude: -157.758,
    name: 'Marine Corps Base Hawaii',
    note: 'Marine Corps air-ground base at Kaneohe Bay.',
    region: 'Indo-Pacific',
    service: 'Marine Corps',
    type: 'Marine Corps base',
  },
  {
    country: 'Hawaii',
    id: 'wheeler-army-airfield',
    latitude: 21.4835,
    location: 'Oahu',
    longitude: -158.039,
    name: 'Wheeler Army Airfield',
    note: 'Army aviation field adjacent to Schofield Barracks.',
    region: 'Indo-Pacific',
    service: 'Army',
    type: 'Army airfield',
  },
  {
    country: 'Hawaii',
    id: 'pohakuloa-training-area',
    latitude: 19.7741,
    location: 'Island of Hawaii',
    longitude: -155.5585,
    name: 'Pohakuloa Training Area',
    note: 'Large maneuver and live-fire training range in Hawaii.',
    region: 'Indo-Pacific',
    service: 'Army',
    type: 'Training area',
  },
  {
    country: 'Alaska',
    id: 'joint-base-elmendorf-richardson',
    latitude: 61.251,
    location: 'Anchorage',
    longitude: -149.807,
    name: 'Joint Base Elmendorf-Richardson',
    note: 'Major Arctic airpower and ground-force hub in Alaska.',
    region: 'Arctic',
    service: 'Joint',
    type: 'Joint base',
  },
  {
    country: 'Alaska',
    id: 'eielson-air-force-base',
    latitude: 64.6657,
    location: 'Fairbanks area',
    longitude: -147.1014,
    name: 'Eielson Air Force Base',
    note: 'Large fighter and Arctic readiness base in interior Alaska.',
    region: 'Arctic',
    service: 'Air Force',
    type: 'Air force base',
  },
  {
    country: 'Alaska',
    id: 'fort-wainwright',
    latitude: 64.8401,
    location: 'Fairbanks',
    longitude: -147.6134,
    name: 'Fort Wainwright',
    note: 'Army installation supporting Arctic and interior-Alaska operations.',
    region: 'Arctic',
    service: 'Army',
    type: 'Army fort',
  },
  {
    country: 'Alaska',
    id: 'fort-greely',
    latitude: 63.9513,
    location: 'Delta Junction',
    longitude: -145.7326,
    name: 'Fort Greely',
    note: 'Missile-defense and Army installation in central Alaska.',
    region: 'Arctic',
    service: 'Army',
    type: 'Army fort',
  },
  {
    country: 'Alaska',
    id: 'clear-space-force-station',
    latitude: 64.2951,
    location: 'Clear',
    longitude: -149.1868,
    name: 'Clear Space Force Station',
    note: 'Strategic radar and missile-warning site in Alaska.',
    region: 'Arctic',
    service: 'Air Force',
    type: 'Space force station',
  },
  {
    country: 'Belgium',
    id: 'usag-benelux-brussels',
    latitude: 50.8776,
    location: 'Brussels / Sterrebeek',
    longitude: 4.4708,
    name: 'USAG Benelux Brussels',
    note: 'Army support site serving the Brussels and NATO-linked military community.',
    region: 'Europe',
    service: 'Army',
    type: 'Army garrison site',
  },
  {
    country: 'Netherlands',
    id: 'usag-benelux-brunssum',
    latitude: 50.9477,
    location: 'Brunssum',
    longitude: 5.9706,
    name: 'USAG Benelux Brunssum',
    note: 'Army support site tied to the Brunssum military and NATO community.',
    region: 'Europe',
    service: 'Army',
    type: 'Army garrison site',
  },
  {
    country: 'Italy',
    id: 'nsa-gricignano-di-aversa',
    latitude: 40.9859,
    location: 'Gricignano di Aversa',
    longitude: 14.2145,
    name: 'Naval Support Activity Gricignano di Aversa',
    note: 'Major support area for U.S. Navy activities in the Naples region.',
    region: 'Europe',
    service: 'Navy',
    type: 'Naval support activity',
  },
  {
    country: 'South Korea',
    id: 'camp-mujuk',
    latitude: 36.0832,
    location: 'Pohang',
    longitude: 129.4032,
    name: 'Camp Mujuk',
    note: 'Marine Corps installation in Korea supporting exercises and regional training.',
    region: 'Indo-Pacific',
    service: 'Marine Corps',
    type: 'Marine Corps camp',
  },
  {
    country: 'Hawaii',
    id: 'fort-shafter',
    latitude: 21.3473,
    location: 'Oahu',
    longitude: -157.8838,
    name: 'Fort Shafter',
    note: 'Headquarters-centered Army post central to U.S. Army Pacific operations.',
    region: 'Indo-Pacific',
    service: 'Army',
    type: 'Army fort',
  },
  {
    country: 'Hawaii',
    id: 'camp-hm-smith',
    latitude: 21.3852,
    location: 'Halawa Heights, Oahu',
    longitude: -157.9327,
    name: 'Camp H.M. Smith',
    note: 'Headquarters site associated with Indo-Pacific joint and Marine command structures.',
    region: 'Indo-Pacific',
    service: 'Joint',
    type: 'Command headquarters',
  },
  {
    country: 'Hawaii',
    id: 'tripler-army-medical-center',
    latitude: 21.3628,
    location: 'Oahu',
    longitude: -157.8903,
    name: 'Tripler Army Medical Center',
    note: 'Major military medical center serving the Pacific theater.',
    region: 'Indo-Pacific',
    service: 'Army',
    type: 'Military medical center',
  },
  {
    country: 'Alaska',
    id: 'eareckson-air-station',
    latitude: 52.7123,
    location: 'Shemya Island',
    longitude: 174.1136,
    name: 'Eareckson Air Station',
    note: 'Remote Aleutian air station with strategic surveillance and support value.',
    region: 'Arctic',
    service: 'Air Force',
    type: 'Air station',
  },
  {
    country: 'Northern Mariana Islands',
    id: 'tinian-north-field',
    latitude: 15.0007,
    location: 'Tinian',
    longitude: 145.6216,
    name: 'North Field Tinian',
    note: 'Strategic Pacific airfield footprint being expanded for U.S. military use.',
    region: 'Indo-Pacific',
    service: 'Air Force',
    type: 'Strategic airfield',
  },
  {
    country: 'Australia',
    id: 'robertson-barracks',
    latitude: -12.5077,
    location: 'Palmerston, Northern Territory',
    longitude: 130.9854,
    name: 'Robertson Barracks',
    note: 'Australian Army base that regularly hosts U.S. Marine Rotational Force-Darwin elements.',
    region: 'Indo-Pacific',
    service: 'Marine Corps',
    type: 'Partner training base',
  },
  {
    country: 'Australia',
    id: 'raaf-base-darwin',
    latitude: -12.4148,
    location: 'Darwin, Northern Territory',
    longitude: 130.8767,
    name: 'RAAF Base Darwin',
    note: 'Australian air base used for allied air exercises and recurring U.S. deployments.',
    region: 'Indo-Pacific',
    service: 'Air Force',
    type: 'Partner air base',
  },
  {
    country: 'Australia',
    id: 'raaf-base-tindal',
    latitude: -14.5214,
    location: 'Katherine, Northern Territory',
    longitude: 132.3782,
    name: 'RAAF Base Tindal',
    note: 'Australian air base tied to enhanced allied air cooperation and U.S. bomber activity.',
    region: 'Indo-Pacific',
    service: 'Air Force',
    type: 'Partner air base',
  },
  {
    country: 'Australia',
    id: 'hmas-stirling',
    latitude: -32.2366,
    location: 'Garden Island, Western Australia',
    longitude: 115.6883,
    name: 'HMAS Stirling',
    note: 'Australian naval base of growing significance for U.S. and allied Indo-Pacific maritime operations.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Partner naval base',
  },
  {
    country: 'Australia',
    id: 'hmas-coonawarra',
    latitude: -12.4545,
    location: 'Darwin, Northern Territory',
    longitude: 130.8118,
    name: 'HMAS Coonawarra',
    note: 'Darwin naval base and logistics point in Australia’s north with growing strategic value.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Partner naval base',
  },
  {
    country: 'Australia',
    id: 'raaf-base-amberley',
    latitude: -27.6408,
    location: 'Queensland',
    longitude: 152.7131,
    name: 'RAAF Base Amberley',
    note: 'Australian air base that has hosted recent U.S. bomber task-force operations.',
    region: 'Indo-Pacific',
    service: 'Air Force',
    type: 'Partner air base',
  },
  {
    country: 'Philippines',
    id: 'antonio-bautista-air-base',
    latitude: 9.739,
    location: 'Puerto Princesa, Palawan',
    longitude: 118.759,
    name: 'Antonio Bautista Air Base',
    note: 'EDCA rotational access site in western Palawan tied to South China Sea operations and disaster response.',
    region: 'Indo-Pacific',
    service: 'Air Force',
    type: 'Partner rotational air base',
  },
  {
    country: 'Philippines',
    id: 'basa-air-base-philippines',
    latitude: 14.93,
    location: 'Floridablanca, Pampanga',
    longitude: 120.493,
    name: 'Basa Air Base',
    note: 'Original EDCA site used for alliance air operations, exercises, and humanitarian response.',
    region: 'Indo-Pacific',
    service: 'Air Force',
    type: 'Partner rotational air base',
  },
  {
    country: 'Philippines',
    id: 'fort-magsaysay-edca',
    latitude: 15.418,
    location: 'Nueva Ecija',
    longitude: 121.056,
    name: 'Fort Magsaysay',
    note: 'EDCA site and major Philippine Army reservation used for rotational training and alliance exercises.',
    region: 'Indo-Pacific',
    service: 'Army',
    type: 'Partner rotational training site',
  },
  {
    country: 'Philippines',
    id: 'mactan-benito-ebuen-air-base',
    latitude: 10.307,
    location: 'Mactan, Cebu',
    longitude: 123.979,
    name: 'Mactan-Benito Ebuen Air Base',
    note: 'EDCA air site in Cebu supporting mobility, exercise, and disaster-response access.',
    region: 'Indo-Pacific',
    service: 'Air Force',
    type: 'Partner rotational air base',
  },
  {
    country: 'Philippines',
    id: 'lumbia-air-base',
    latitude: 8.415,
    location: 'Cagayan de Oro',
    longitude: 124.611,
    name: 'Lumbia Air Base',
    note: 'EDCA site in Mindanao used for rotational access and humanitarian assistance / disaster response.',
    region: 'Indo-Pacific',
    service: 'Air Force',
    type: 'Partner rotational air base',
  },
  {
    country: 'Philippines',
    id: 'naval-base-camilo-osias',
    latitude: 18.486,
    location: 'Santa Ana, Cagayan',
    longitude: 122.147,
    name: 'Naval Base Camilo Osias',
    note: 'Additional EDCA site announced in 2023, giving rotational access near the Luzon Strait.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Partner access naval base',
  },
  {
    country: 'Philippines',
    id: 'camp-melchor-dela-cruz',
    latitude: 16.899,
    location: 'Gamu, Isabela',
    longitude: 121.836,
    name: 'Camp Melchor Dela Cruz',
    note: 'Additional EDCA site in northern Luzon supporting rotational ground-force access and exercises.',
    region: 'Indo-Pacific',
    service: 'Army',
    type: 'Partner rotational army camp',
  },
  {
    country: 'Philippines',
    id: 'balabac-island-edca',
    latitude: 7.986,
    location: 'Balabac, Palawan',
    longitude: 117.048,
    name: 'Balabac Island',
    note: 'Additional EDCA location in southern Palawan with strategic access toward the Sulu and South China Sea approaches.',
    region: 'Indo-Pacific',
    service: 'Joint',
    type: 'Partner access island site',
  },
  {
    country: 'Philippines',
    id: 'lal-lo-airport',
    latitude: 18.178,
    location: 'Lal-lo, Cagayan',
    longitude: 121.745,
    name: 'Lal-lo Airport',
    note: 'Additional EDCA airfield in northern Luzon for rotational access, mobility, and contingency support.',
    region: 'Indo-Pacific',
    service: 'Air Force',
    type: 'Partner access airfield',
  },
  {
    country: 'Norway',
    id: 'rygge-air-station',
    latitude: 59.378,
    location: 'Rygge',
    longitude: 10.786,
    name: 'Rygge Air Station',
    note: 'Original Norway SDCA agreed facility for U.S. and allied access.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Partner access air station',
  },
  {
    country: 'Norway',
    id: 'sola-air-station',
    latitude: 58.876,
    location: 'Sola',
    longitude: 5.637,
    name: 'Sola Air Station',
    note: 'Original Norway SDCA agreed facility on the southwest coast.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Partner access air station',
  },
  {
    country: 'Norway',
    id: 'evenes-air-station',
    latitude: 68.491,
    location: 'Evenes',
    longitude: 16.678,
    name: 'Evenes Air Station',
    note: 'Original Norway SDCA agreed air station in the High North.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Partner access air station',
  },
  {
    country: 'Norway',
    id: 'ramsund-naval-station',
    latitude: 68.476,
    location: 'Ramsund',
    longitude: 17.422,
    name: 'Ramsund Naval Station',
    note: 'Original Norway SDCA agreed naval station for maritime access in northern Norway.',
    region: 'Europe',
    service: 'Navy',
    type: 'Partner access naval station',
  },
  {
    country: 'Norway',
    id: 'andoya-air-station',
    latitude: 69.292,
    location: 'Andøya',
    longitude: 16.144,
    name: 'Andøya Air Station and Airfield',
    note: 'Additional Norway SDCA agreed facility adopted in 2024.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Partner access air station',
  },
  {
    country: 'Norway',
    id: 'orland-air-station',
    latitude: 63.699,
    location: 'Ørland',
    longitude: 9.604,
    name: 'Ørland Air Station and Airfield',
    note: 'Additional Norway SDCA agreed air station used by Norway and allied air forces.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Partner access air station',
  },
  {
    country: 'Norway',
    id: 'haakonsvern-naval-station',
    latitude: 60.317,
    location: 'Bergen area',
    longitude: 5.226,
    name: 'Haakonsvern Naval Station',
    note: 'Additional Norway SDCA agreed naval station near Bergen.',
    region: 'Europe',
    service: 'Navy',
    type: 'Partner access naval station',
  },
  {
    country: 'Norway',
    id: 'vaernes-garrison',
    latitude: 63.457,
    location: 'Værnes',
    longitude: 10.923,
    name: 'Værnes Garrison, Air Station and Airfield',
    note: 'Additional Norway SDCA agreed area linking garrison and airfield access.',
    region: 'Europe',
    service: 'Army',
    type: 'Partner access garrison',
  },
  {
    country: 'Norway',
    id: 'bardufoss-air-station',
    latitude: 69.055,
    location: 'Bardufoss',
    longitude: 18.541,
    name: 'Bardufoss Air Station and Airfield',
    note: 'Additional Norway SDCA agreed air station in Troms.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Partner access air station',
  },
  {
    country: 'Norway',
    id: 'setermoen-garrison',
    latitude: 68.861,
    location: 'Setermoen',
    longitude: 18.349,
    name: 'Setermoen Garrison',
    note: 'Additional Norway SDCA agreed garrison with firing range and exercise area.',
    region: 'Europe',
    service: 'Army',
    type: 'Partner access garrison',
  },
  {
    country: 'Norway',
    id: 'osmarka-cave-complex',
    latitude: 67.259,
    location: 'Fauske area',
    longitude: 15.394,
    name: 'Osmarka Cave Complex',
    note: 'Additional Norway SDCA agreed storage and support site.',
    region: 'Europe',
    service: 'Joint',
    type: 'Partner access cave complex',
  },
  {
    country: 'Norway',
    id: 'namsen-fuel-terminal',
    latitude: 64.466,
    location: 'Namsos area',
    longitude: 11.495,
    name: 'Namsen Fuel Terminal',
    note: 'Additional Norway SDCA agreed fuel and sustainment site.',
    region: 'Europe',
    service: 'Joint',
    type: 'Partner access fuel terminal',
  },
  {
    country: 'Oman',
    id: 'port-of-duqm',
    latitude: 19.667,
    location: 'Duqm',
    longitude: 57.709,
    name: 'Port of Duqm',
    note: 'Public U.S.-Oman access port under the 2019 expansion of facilities access arrangements.',
    region: 'Middle East',
    service: 'Navy',
    type: 'Partner access port',
  },
  {
    country: 'Oman',
    id: 'port-of-salalah',
    latitude: 16.949,
    location: 'Salalah',
    longitude: 54.004,
    name: 'Port of Salalah',
    note: 'Public U.S.-Oman access port under the 2019 strategic framework expansion.',
    region: 'Middle East',
    service: 'Navy',
    type: 'Partner access port',
  },
  {
    country: 'Oman',
    id: 'rafo-thumrait',
    latitude: 17.666,
    location: 'Thumrait',
    longitude: 54.024,
    name: 'RAFO Thumrait',
    note: 'Long-public Omani air base covered by U.S.-Oman facilities access arrangements.',
    region: 'Middle East',
    service: 'Air Force',
    type: 'Partner access air base',
  },
  {
    country: 'Oman',
    id: 'rafo-masirah',
    latitude: 20.675,
    location: 'Masirah Island',
    longitude: 58.89,
    name: 'RAFO Masirah',
    note: 'Long-public Omani access air base on Masirah Island.',
    region: 'Middle East',
    service: 'Air Force',
    type: 'Partner access air base',
  },
  {
    country: 'Oman',
    id: 'khasab-airfield',
    latitude: 26.171,
    location: 'Khasab',
    longitude: 56.241,
    name: 'Khasab Airfield',
    note: 'Public access facility cited in longstanding U.S.-Oman arrangements.',
    region: 'Middle East',
    service: 'Air Force',
    type: 'Partner access airfield',
  },
  {
    country: 'Oman',
    id: 'raysut-port',
    latitude: 16.93,
    location: 'Raysut, Salalah area',
    longitude: 54.002,
    name: 'Raysut Port',
    note: 'Public access port / logistics site cited in longstanding U.S.-Oman arrangements.',
    region: 'Middle East',
    service: 'Navy',
    type: 'Partner access port',
  },
  {
    country: 'Iceland',
    id: 'keflavik-air-base',
    latitude: 63.9658,
    location: 'Reykjanesbær',
    longitude: -22.595,
    name: 'Keflavik Air Base',
    note: 'Icelandic air base used for recurring U.S. and NATO air, refueling, and Arctic posture operations.',
    region: 'Arctic',
    service: 'Air Force',
    type: 'Partner access air base',
  },
  {
    country: 'Finland',
    id: 'ivalo-border-guard-base',
    latitude: 68.6083,
    location: 'Ivalo',
    longitude: 27.4209,
    name: 'Ivalo Border Guard Base and Airport',
    note: 'Named in Finland’s DCA annex as a High North access point for U.S. forces in Finnish Lapland.',
    region: 'Arctic',
    service: 'Joint',
    type: 'Partner access border guard base',
  },
  {
    country: 'Finland',
    id: 'rovajarvi-training-area',
    latitude: 66.6833,
    location: 'Lapland',
    longitude: 26.5861,
    name: 'Rovajarvi Training Area',
    note: 'Large Finnish live-fire and maneuver area listed in the DCA annex for potential U.S. use.',
    region: 'Arctic',
    service: 'Army',
    type: 'Partner access training area',
  },
  {
    country: 'Finland',
    id: 'rovaniemi-air-base',
    latitude: 66.5648,
    location: 'Rovaniemi',
    longitude: 25.8312,
    name: 'Rovaniemi Air Base and Jaeger Brigade Garrison',
    note: 'Finnish Lapland air-and-garrison site named in the DCA annex for U.S. access.',
    region: 'Arctic',
    service: 'Joint',
    type: 'Partner access air base',
  },
  {
    country: 'Sweden',
    id: 'lulea-air-base',
    latitude: 65.5478,
    location: 'Kallax, Luleå',
    longitude: 22.1167,
    name: 'Lulea Air Base',
    note: 'Northern Swedish air base listed in Sweden’s DCA annex for U.S. access.',
    region: 'Arctic',
    service: 'Air Force',
    type: 'Partner access air base',
  },
  {
    country: 'Sweden',
    id: 'boden-regimental-area',
    latitude: 65.826,
    location: 'Boden',
    longitude: 21.69,
    name: 'Boden Regimental Area and Exercise Area',
    note: 'Swedish Army area in the north named in the DCA annex as an agreed facility and exercise area.',
    region: 'Arctic',
    service: 'Army',
    type: 'Partner access regimental area',
  },
  {
    country: 'Sweden',
    id: 'kiruna-military-camp',
    latitude: 67.856,
    location: 'Kiruna',
    longitude: 20.225,
    name: 'Kiruna Military Camp and Exercise Area',
    note: 'High North Swedish camp and training area listed in the DCA annex for U.S. access.',
    region: 'Arctic',
    service: 'Army',
    type: 'Partner access military camp',
  },
  {
    country: 'Sweden',
    id: 'vidsel-airport-test-range',
    latitude: 65.8753,
    location: 'Vidsel',
    longitude: 20.15,
    name: 'Vidsel Airport and Test Range',
    note: 'Northern Swedish air-and-test site named in the DCA annex and useful for Arctic-range activity.',
    region: 'Arctic',
    service: 'Air Force',
    type: 'Partner access test range',
  },
  {
    country: 'Papua New Guinea',
    id: 'lombrum-naval-base',
    latitude: -2.0306,
    location: 'Los Negros Island, Manus',
    longitude: 147.2722,
    name: 'Lombrum Naval Base',
    note: 'Named PNG DCA facility on Manus tied to U.S. and allied maritime access and recapitalization work.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Partner access naval base',
  },
  {
    country: 'Papua New Guinea',
    id: 'momote-airport',
    latitude: -2.0629,
    location: 'Los Negros Island, Manus',
    longitude: 147.4244,
    name: 'Momote Airport',
    note: 'Named PNG DCA airfield on Manus associated with access, mobility, and contingency support.',
    region: 'Indo-Pacific',
    service: 'Air Force',
    type: 'Partner access airfield',
  },
  {
    country: 'Papua New Guinea',
    id: 'jacksons-international-airport',
    latitude: -9.4403,
    location: 'Port Moresby',
    longitude: 147.2171,
    name: 'Jacksons International Airport',
    note: 'Named PNG DCA airport in the capital used for access, lift, and defense logistics.',
    region: 'Indo-Pacific',
    service: 'Air Force',
    type: 'Partner access airport',
  },
  {
    country: 'Papua New Guinea',
    id: 'port-moresby-seaport',
    latitude: -9.4746,
    location: 'Port Moresby',
    longitude: 147.1471,
    name: 'Port Moresby Seaport',
    note: 'Named PNG DCA seaport in the capital for maritime logistics and access.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Partner access seaport',
  },
  {
    country: 'Papua New Guinea',
    id: 'nadzab-tomodachi-international-airport',
    latitude: -6.5655,
    location: 'Nadzab, Morobe',
    longitude: 146.7303,
    name: 'Nadzab Tomodachi International Airport',
    note: 'Named PNG DCA airport near Lae tied to runway, mobility, and logistics access.',
    region: 'Indo-Pacific',
    service: 'Air Force',
    type: 'Partner access airport',
  },
  {
    country: 'Papua New Guinea',
    id: 'lae-seaport',
    latitude: -6.7333,
    location: 'Lae, Morobe',
    longitude: 147,
    name: 'Lae Seaport',
    note: 'Named PNG DCA seaport near the Highlands logistics corridor and Morobe coast.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Partner access seaport',
  },
  {
    country: 'Palau',
    id: 'palau-international-airport',
    latitude: 7.3669,
    location: 'Airai',
    longitude: 134.5443,
    name: 'Palau International Airport',
    note: 'Publicly documented Palau runway and apron site tied to U.S. military engineering and access work.',
    region: 'Indo-Pacific',
    service: 'Air Force',
    type: 'Partner access airport',
  },
  {
    country: 'Palau',
    id: 'peleliu-airstrip',
    latitude: 6.9953,
    location: 'Peleliu',
    longitude: 134.2294,
    name: 'Peleliu Airstrip',
    note: 'Historic Palau runway site publicly cleared and improved for renewed U.S. access and expeditionary use.',
    region: 'Indo-Pacific',
    service: 'Marine Corps',
    type: 'Partner access airstrip',
  },
  {
    country: 'United Arab Emirates',
    id: 'jebel-ali-port',
    latitude: 24.9805,
    location: 'Dubai',
    longitude: 55.0599,
    name: 'Jebel Ali Port',
    note: 'Major Gulf port frequently described by the U.S. Navy as its busiest foreign liberty and logistics port.',
    region: 'Middle East',
    service: 'Navy',
    type: 'Partner access port',
  },
  {
    country: 'United Arab Emirates',
    id: 'al-minhad-base',
    latitude: 25.0228,
    location: 'Dubai area',
    longitude: 55.3636,
    name: 'Al Minhad Base',
    note: 'Publicly used coalition and partner air base in the UAE associated with U.S. regional transit and sustainment.',
    region: 'Middle East',
    service: 'Air Force',
    type: 'Partner access air base',
  },
  {
    country: 'United Arab Emirates',
    id: 'port-of-fujairah',
    latitude: 25.1861,
    location: 'Fujairah',
    longitude: 56.3555,
    name: 'Port of Fujairah',
    note: 'Gulf of Oman logistics port used in major U.S.-partner sustainment exercises and maritime access planning.',
    region: 'Middle East',
    service: 'Navy',
    type: 'Partner access port',
  },
  {
    country: 'Saudi Arabia',
    id: 'yanbu-port',
    latitude: 24.0803,
    location: 'Yanbu',
    longitude: 38.0659,
    name: 'Yanbu Port',
    note: 'Red Sea logistics port used in publicly announced large-scale U.S.-partner sustainment exercises.',
    region: 'Middle East',
    service: 'Navy',
    type: 'Partner access port',
  },
  {
    country: 'Bahrain',
    id: 'sheikh-isa-air-base',
    latitude: 25.9177,
    location: 'Southern Governorate',
    longitude: 50.5877,
    name: 'Sheikh Isa Air Base',
    note: 'Bahraini air base publicly associated with U.S. partner logistics and air sustainment activity.',
    region: 'Middle East',
    service: 'Air Force',
    type: 'Partner access air base',
  },
  {
    country: 'Bahrain',
    id: 'riffa-army-base',
    latitude: 26.135,
    location: 'Riffa',
    longitude: 50.5455,
    name: 'Riffa Army Base',
    note: 'Public Bahrain army site referenced in U.S.-partner logistics exercise reporting and contracting activity.',
    region: 'Middle East',
    service: 'Army',
    type: 'Partner access army base',
  },
  {
    country: 'Bahrain',
    id: 'naval-support-activity-muharraq',
    latitude: 26.2708,
    location: 'Muharraq',
    longitude: 50.6336,
    name: 'Naval Support Activity Muharraq',
    note: 'Distinct Bahrain support point near the airfield corridor referenced in U.S. regional logistics activity.',
    region: 'Middle East',
    service: 'Navy',
    type: 'Partner access naval support activity',
  },
  {
    country: 'Finland',
    id: 'kuopio-rissala-air-base',
    latitude: 63.0088,
    location: 'Siilinjärvi / Kuopio',
    longitude: 27.7891,
    name: 'Kuopio-Rissala Air Base',
    note: 'Finnish DCA annex site tied to Air Force operations and agreed U.S. access in eastern Finland.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Partner access air base',
  },
  {
    country: 'Finland',
    id: 'tampere-pirkkala-air-base',
    latitude: 61.4141,
    location: 'Pirkkala / Tampere',
    longitude: 23.6045,
    name: 'Tampere-Pirkkala Air Base',
    note: 'Named in Finland’s DCA annex as a major aviation access point in the south-west.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Partner access air base',
  },
  {
    country: 'Finland',
    id: 'jyvaskyla-tikkakoski-air-base',
    latitude: 62.3993,
    location: 'Jyväskylä / Tikkakoski',
    longitude: 25.6759,
    name: 'Jyväskylä-Tikkakoski Air Base',
    note: 'Finnish DCA annex site associated with Air Force Academy functions and U.S. access rights.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Partner access air base',
  },
  {
    country: 'Finland',
    id: 'upinniemi-naval-base',
    latitude: 60.0208,
    location: 'Kirkkonummi',
    longitude: 24.3389,
    name: 'Upinniemi Navy Base and Garrison',
    note: 'Named Finnish naval access site in the DCA annex on the Gulf of Finland approaches.',
    region: 'Europe',
    service: 'Navy',
    type: 'Partner access naval base',
  },
  {
    country: 'Finland',
    id: 'vekaranjarvi-garrison',
    latitude: 61.1143,
    location: 'Kouvola area',
    longitude: 27.0205,
    name: 'Vekaranjärvi Garrison and Training Area',
    note: 'Finnish Army garrison and training complex listed in the DCA annex for agreed U.S. access.',
    region: 'Europe',
    service: 'Army',
    type: 'Partner access garrison',
  },
  {
    country: 'Finland',
    id: 'niinisalo-garrison',
    latitude: 61.8455,
    location: 'Kankaanpää',
    longitude: 22.4678,
    name: 'Niinisalo Garrison and Training Areas',
    note: 'DCA annex Army site in western Finland tied to range and maneuver access.',
    region: 'Europe',
    service: 'Army',
    type: 'Partner access garrison',
  },
  {
    country: 'Finland',
    id: 'raasepori-dragsvik-garrison',
    latitude: 59.9902,
    location: 'Dragsvik / Raseborg',
    longitude: 23.4886,
    name: 'Raasepori Garrison and Syndalen Training Area',
    note: 'Finnish coastal training and garrison site named in the DCA annex for agreed access.',
    region: 'Europe',
    service: 'Army',
    type: 'Partner access garrison',
  },
  {
    country: 'Sweden',
    id: 'ronneby-air-base',
    latitude: 56.2686,
    location: 'Ronneby',
    longitude: 15.2727,
    name: 'Ronneby Air Base',
    note: 'Swedish DCA annex air base in Blekinge supporting agreed U.S. access.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Partner access air base',
  },
  {
    country: 'Sweden',
    id: 'satenas-air-base',
    latitude: 58.4312,
    location: 'Såtenäs',
    longitude: 12.7068,
    name: 'Såtenäs Air Base',
    note: 'Swedish DCA annex air base used by the Swedish Air Force and opened for agreed U.S. access.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Partner access air base',
  },
  {
    country: 'Sweden',
    id: 'uppsala-air-base',
    latitude: 59.9228,
    location: 'Uppsala',
    longitude: 17.5367,
    name: 'Uppsala Air Base',
    note: 'Named Swedish DCA annex air site in central Sweden for agreed U.S. access.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Partner access air base',
  },
  {
    country: 'Sweden',
    id: 'halmstad-regimental-area',
    latitude: 56.6913,
    location: 'Halmstad',
    longitude: 12.8206,
    name: 'Halmstad Regimental Area and Air Base',
    note: 'Swedish DCA annex facility in Halland combining regimental and aviation infrastructure.',
    region: 'Europe',
    service: 'Joint',
    type: 'Partner access regimental area',
  },
  {
    country: 'Sweden',
    id: 'revingehed-regimental-area',
    latitude: 55.6898,
    location: 'Revingehed, Skåne',
    longitude: 13.4354,
    name: 'Revingehed Regimental Area',
    note: 'Swedish DCA annex training and regimental area in southern Sweden.',
    region: 'Europe',
    service: 'Army',
    type: 'Partner access regimental area',
  },
  {
    country: 'Sweden',
    id: 'visby-military-area',
    latitude: 57.6654,
    location: 'Visby, Gotland',
    longitude: 18.3471,
    name: 'Visby Airport and Military Area',
    note: 'Gotland-based DCA annex site central to Baltic Sea access and reinforcement planning.',
    region: 'Europe',
    service: 'Joint',
    type: 'Partner access military area',
  },
  {
    country: 'Sweden',
    id: 'berga-naval-base',
    latitude: 59.0946,
    location: 'Haninge',
    longitude: 18.1109,
    name: 'Berga Naval Base',
    note: 'Swedish DCA annex naval site south of Stockholm tied to maritime support and access.',
    region: 'Europe',
    service: 'Navy',
    type: 'Partner access naval base',
  },
  {
    country: 'Sweden',
    id: 'ravlunda-military-camp',
    latitude: 55.7101,
    location: 'Ravlunda, Skåne',
    longitude: 14.1513,
    name: 'Ravlunda Military Camp and Exercise Area',
    note: 'Swedish DCA annex coastal training and exercise area in southern Sweden.',
    region: 'Europe',
    service: 'Army',
    type: 'Partner access military camp',
  },
  {
    country: 'Australia',
    id: 'bradshaw-field-training-area',
    latitude: -15.2035,
    location: 'Northern Territory',
    longitude: 130.4062,
    name: 'Bradshaw Field Training Area',
    note: 'Large Australian maneuver range used in public U.S.-Australia exercises and rotational training.',
    region: 'Indo-Pacific',
    service: 'Marine Corps',
    type: 'Partner training area',
  },
  {
    country: 'Australia',
    id: 'raaf-base-scherger',
    latitude: -12.6558,
    location: 'Cape York, Queensland',
    longitude: 142.0858,
    name: 'RAAF Base Scherger',
    note: 'Northern Australian bare base with public relevance to allied dispersal and access planning.',
    region: 'Indo-Pacific',
    service: 'Air Force',
    type: 'Partner air base',
  },
  {
    country: 'Australia',
    id: 'raaf-base-learmonth',
    latitude: -22.228,
    location: 'Exmouth, Western Australia',
    longitude: 114.0854,
    name: 'RAAF Base Learmonth',
    note: 'Western Australian air base publicly used in allied operations and contingency posture planning.',
    region: 'Indo-Pacific',
    service: 'Air Force',
    type: 'Partner air base',
  },
  {
    country: 'Australia',
    id: 'raaf-base-curtin',
    latitude: -17.608,
    location: 'Kimberley, Western Australia',
    longitude: 123.8232,
    name: 'RAAF Base Curtin',
    note: 'Remote northern Australian bare base tied to public allied air dispersal and readiness concepts.',
    region: 'Indo-Pacific',
    service: 'Air Force',
    type: 'Partner air base',
  },
  {
    country: 'Australia',
    id: 'hmas-cairns',
    latitude: -16.936,
    location: 'Cairns, Queensland',
    longitude: 145.7783,
    name: 'HMAS Cairns',
    note: 'Queensland naval base of growing relevance to Pacific and Coral Sea partner operations.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Partner naval base',
  },
  {
    country: 'Australia',
    id: 'cocos-keeling-islands-airport',
    latitude: -12.188,
    location: 'West Island, Cocos (Keeling) Islands',
    longitude: 96.8292,
    name: 'Cocos (Keeling) Islands Airport',
    note: 'Indian Ocean runway site publicly discussed for allied surveillance, access, and resilience upgrades.',
    region: 'Indo-Pacific',
    service: 'Joint',
    type: 'Partner access airport',
  },
  {
    country: 'Palau',
    id: 'angaur-airstrip',
    latitude: 6.9048,
    location: 'Angaur',
    longitude: 134.1429,
    name: 'Angaur Airstrip',
    note: 'Public Palau runway site relevant to U.S. western-Pacific access and expeditionary airfield concepts.',
    region: 'Indo-Pacific',
    service: 'Joint',
    type: 'Partner access airstrip',
  },
  {
    country: 'Finland',
    id: 'joensuu-airport',
    latitude: 62.6597,
    location: 'Joensuu',
    longitude: 29.6216,
    name: 'Joensuu Airport and Associated Areas',
    note: 'Named in Finland’s DCA annex as an agreed aviation access point in eastern Finland.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Partner access airport',
  },
  {
    country: 'Finland',
    id: 'kajaani-airport',
    latitude: 64.2832,
    location: 'Kajaani',
    longitude: 27.6792,
    name: 'Kajaani Airport and Associated Areas',
    note: 'Official Finland DCA annex airport site in Kainuu for agreed U.S. access.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Partner access airport',
  },
  {
    country: 'Finland',
    id: 'kokkola-pietarsaari-airport',
    latitude: 63.7192,
    location: 'Kruunupyy / Kokkola-Pietarsaari',
    longitude: 23.1404,
    name: 'Kokkola-Pietarsaari Airport and Associated Areas',
    note: 'Official Finland DCA annex airport on the west coast for agreed access.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Partner access airport',
  },
  {
    country: 'Finland',
    id: 'pohjankangas-military-area',
    latitude: 61.8455,
    location: 'Kankaanpää',
    longitude: 22.4678,
    name: 'Pohjankangas Military Area and Associated Areas',
    note: 'Official Finland DCA annex military area in Satakunta tied to training and maneuver access.',
    region: 'Europe',
    service: 'Army',
    type: 'Partner access military area',
  },
  {
    country: 'Finland',
    id: 'parkano-military-storage-area',
    latitude: 62.0106,
    location: 'Parkano',
    longitude: 23.0187,
    name: 'Parkano Military Storage Area',
    note: 'One of the storage locations named in Finland’s DCA annex.',
    region: 'Europe',
    service: 'Joint',
    type: 'Partner access storage area',
  },
  {
    country: 'Finland',
    id: 'skinnarvik-military-storage-area',
    latitude: 60.1333,
    location: 'Kimitoön',
    longitude: 22.4583,
    name: 'Skinnarvik Military Storage Area',
    note: 'One of the storage locations named in Finland’s DCA annex.',
    region: 'Europe',
    service: 'Joint',
    type: 'Partner access storage area',
  },
  {
    country: 'Finland',
    id: 'tammela-military-storage-area',
    latitude: 60.8088,
    location: 'Tammela',
    longitude: 23.7598,
    name: 'Tammela Military Storage Area',
    note: 'One of the storage locations named in Finland’s DCA annex.',
    region: 'Europe',
    service: 'Joint',
    type: 'Partner access storage area',
  },
  {
    country: 'Finland',
    id: 'tervola-military-storage-area',
    latitude: 66.0823,
    location: 'Tervola',
    longitude: 24.8059,
    name: 'Tervola Military Storage Area',
    note: 'One of the storage locations named in Finland’s DCA annex.',
    region: 'Arctic',
    service: 'Joint',
    type: 'Partner access storage area',
  },
  {
    country: 'Finland',
    id: 'veitsiluoto-military-storage-area',
    latitude: 65.6915,
    location: 'Kemi / Veitsiluoto',
    longitude: 24.6243,
    name: 'Veitsiluoto Military Storage Area',
    note: 'One of the storage locations named in Finland’s DCA annex near the Gulf of Bothnia.',
    region: 'Arctic',
    service: 'Joint',
    type: 'Partner access storage area',
  },
  {
    country: 'Sweden',
    id: 'harnosand-port-and-area',
    latitude: 62.6323,
    location: 'Härnösand',
    longitude: 17.938,
    name: 'Härnösand Port and Associated Area',
    note: 'Official Sweden DCA annex site on the Gulf of Bothnia coast.',
    region: 'Europe',
    service: 'Navy',
    type: 'Partner access port',
  },
  {
    country: 'Sweden',
    id: 'kristinehamn-area',
    latitude: 59.3114,
    location: 'Kristinehamn',
    longitude: 14.1118,
    name: 'Kristinehamn Associated Area',
    note: 'Official Sweden DCA annex inland support area in Värmland.',
    region: 'Europe',
    service: 'Joint',
    type: 'Partner access support area',
  },
  {
    country: 'Sweden',
    id: 'kvarn-military-camp',
    latitude: 58.6339,
    location: 'Kvarn, Östergötland',
    longitude: 15.3086,
    name: 'Kvarn Military Camp and Exercise Area',
    note: 'Official Sweden DCA annex Army training and exercise site.',
    region: 'Europe',
    service: 'Army',
    type: 'Partner access military camp',
  },
  {
    country: 'Sweden',
    id: 'alvdalen-military-camp',
    latitude: 61.3333,
    location: 'Älvdalen',
    longitude: 13.75,
    name: 'Älvdalen Military Camp and Exercise Area',
    note: 'Official Sweden DCA annex camp and exercise area in Dalarna.',
    region: 'Europe',
    service: 'Army',
    type: 'Partner access military camp',
  },
  {
    country: 'Sweden',
    id: 'ostersund-military-camp',
    latitude: 63.1794,
    location: 'Östersund',
    longitude: 14.6357,
    name: 'Östersund Military Camp and Exercise Areas',
    note: 'Official Sweden DCA annex site in Jämtland for agreed U.S. access.',
    region: 'Europe',
    service: 'Army',
    type: 'Partner access military camp',
  },
  {
    country: 'Philippines',
    id: 'subic-bay-freeport',
    latitude: 14.8211,
    location: 'Subic Bay, Zambales',
    longitude: 120.2813,
    name: 'Subic Bay Freeport and Harbor',
    note: 'Publicly used port-and-logistics node in the Philippines tied to recurring U.S. access, ship activity, and fuel-storage planning.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Partner access port',
  },
  {
    country: 'Philippines',
    id: 'naval-detachment-oyster-bay',
    latitude: 10.0667,
    location: 'Quezon, Palawan',
    longitude: 118.7333,
    name: 'Naval Detachment Oyster Bay',
    note: 'Publicly discussed Palawan boat-maintenance and maritime-access site near the South China Sea approaches.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Partner maritime support site',
  },
  {
    country: 'Philippines',
    id: 'puerto-princesa-port',
    latitude: 9.7435,
    location: 'Puerto Princesa, Palawan',
    longitude: 118.7277,
    name: 'Puerto Princesa Port',
    note: 'Public Palawan seaport relevant to allied maritime logistics and exercise access in western Philippines.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Partner access port',
  },
  {
    country: 'Palau',
    id: 'malakal-port',
    latitude: 7.3336,
    location: 'Koror / Malakal',
    longitude: 134.4528,
    name: 'Malakal Port',
    note: 'Public port facility in Koror used in U.S.-Palau engineering and sustainment activity.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Partner access port',
  },
  {
    country: 'Palau',
    id: 'peleliu-south-dock',
    latitude: 6.9854,
    location: 'Peleliu',
    longitude: 134.2214,
    name: 'Peleliu South Dock',
    note: 'Public dock site on Peleliu relevant to maritime sustainment and expeditionary access planning.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Partner access dock',
  },
  {
    country: 'Kuwait',
    id: 'kuwait-international-airport-cargo-city',
    latitude: 29.2314,
    location: 'Kuwait International Airport',
    longitude: 47.9798,
    name: 'Kuwait International Airport Cargo City',
    note: 'Publicly named cargo and sustainment hub linked to U.S. regional logistics activity in Kuwait.',
    region: 'Middle East',
    service: 'Air Force',
    type: 'Partner logistics airfield',
  },
  {
    country: 'Kuwait',
    id: 'port-of-shuaiba',
    latitude: 29.0442,
    location: 'Shuaiba',
    longitude: 48.1214,
    name: 'Port of Shuaiba',
    note: 'Publicly named Kuwaiti logistics port used in U.S.-partner sustainment exercises.',
    region: 'Middle East',
    service: 'Navy',
    type: 'Partner access port',
  },
  {
    country: 'Kuwait',
    id: 'kuwait-naval-base',
    latitude: 28.8618,
    location: 'Al Zour coast',
    longitude: 48.275,
    name: 'Kuwait Naval Base',
    note: 'Publicly named Kuwaiti naval base appearing in U.S. defense construction and budget documentation.',
    region: 'Middle East',
    service: 'Navy',
    type: 'Partner naval base',
  },
  {
    country: 'Denmark',
    id: 'aalborg-air-base',
    latitude: 57.0864,
    location: 'Aalborg',
    longitude: 9.868,
    name: 'Aalborg Air Base',
    note: 'Named in Denmark’s defense cooperation agreement with the United States as an agreed air base for U.S. access.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Partner access air base',
  },
  {
    country: 'Denmark',
    id: 'karup-air-base',
    latitude: 56.3112,
    location: 'Karup',
    longitude: 9.1238,
    name: 'Karup Air Base',
    note: 'Named in Denmark’s defense cooperation agreement with the United States as an agreed air base for U.S. access.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Partner access air base',
  },
  {
    country: 'Denmark',
    id: 'skrydstrup-air-base',
    latitude: 55.2214,
    location: 'Skrydstrup / Vojens',
    longitude: 9.2916,
    name: 'Skrydstrup Air Base',
    note: 'Named in Denmark’s defense cooperation agreement with the United States as an agreed air base for U.S. access.',
    region: 'Europe',
    service: 'Air Force',
    type: 'Partner access air base',
  },
  {
    country: 'Greenland',
    id: 'kangerlussuaq-airport',
    latitude: 67.0113,
    location: 'Kangerlussuaq',
    longitude: -50.7075,
    name: 'Kangerlussuaq Airport',
    note: 'Public Arctic airfield in Greenland used in allied and U.S.-linked logistics and support activity.',
    region: 'Arctic',
    service: 'Air Force',
    type: 'Partner access airport',
  },
  {
    country: 'Philippines',
    id: 'ulugan-bay-maritime-zone',
    latitude: 10.085,
    location: 'Puerto Princesa, Palawan',
    longitude: 118.7969,
    name: 'Ulugan Bay Maritime Access Zone',
    note: 'Publicly discussed Palawan maritime-security bay linked to the broader Oyster Bay / western-Palawan naval access area.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Partner maritime access bay',
  },
  {
    country: 'Kuwait',
    id: 'ahmad-al-jaber-air-base',
    latitude: 28.9325,
    location: 'Kuwait',
    longitude: 47.7827,
    name: 'Ahmad Al Jaber Air Base',
    note: 'Publicly used Kuwaiti air base tied to U.S. Air Forces Central sustainment and regional air operations.',
    region: 'Middle East',
    service: 'Air Force',
    type: 'Partner access air base',
  },
  {
    country: 'Qatar',
    id: 'hamad-port',
    latitude: 25.0337,
    location: 'Mesaieed / Doha area',
    longitude: 51.5824,
    name: 'Hamad Port',
    note: 'Public Qatari port that has hosted U.S. naval visits and regional maritime logistics activity.',
    region: 'Middle East',
    service: 'Navy',
    type: 'Partner access port',
  },
  {
    country: 'Greenland',
    id: 'station-nord',
    latitude: 81.6011,
    location: 'Northeast Greenland',
    longitude: -16.6583,
    name: 'Station Nord',
    note: 'Public Danish Arctic station and airstrip in northeast Greenland with relevance to allied logistics and High North support.',
    region: 'Arctic',
    service: 'Joint',
    type: 'Partner Arctic station',
  },
  {
    country: 'Greenland',
    id: 'mestersvig-airport',
    latitude: 72.2369,
    location: 'Mestersvig',
    longitude: -23.9319,
    name: 'Mestersvig Airport',
    note: 'Public Danish Arctic airfield in east Greenland relevant to allied logistics and remote support operations.',
    region: 'Arctic',
    service: 'Joint',
    type: 'Partner access airport',
  },
  {
    country: 'Philippines',
    id: 'naval-station-carlito-cunanan',
    latitude: 10.0165,
    location: 'Macarascas, Puerto Princesa, Palawan',
    longitude: 118.808,
    name: 'Naval Station Carlito Cunanan',
    note: 'Public Palawan naval outpost in the western maritime belt linked to Oyster Bay and South China Sea-facing patrol activity.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Partner naval station',
  },
  {
    country: 'Kuwait',
    id: 'abdullah-al-mubarak-air-base',
    latitude: 29.2314,
    location: 'Kuwait International Airport area',
    longitude: 47.9798,
    name: 'Abdullah Al-Mubarak Air Base',
    note: 'Publicly named Kuwaiti air base co-located with major U.S.-linked logistics flows around Cargo City.',
    region: 'Middle East',
    service: 'Air Force',
    type: 'Partner access air base',
  },
  {
    country: 'Bahrain',
    id: 'mina-salman-port',
    latitude: 26.2018,
    location: 'Manama',
    longitude: 50.6081,
    name: 'Mina Salman Port',
    note: 'Public Bahraini port that has hosted U.S. naval visits and regional sustainment traffic.',
    region: 'Middle East',
    service: 'Navy',
    type: 'Partner access port',
  },
  {
    country: 'Bahrain',
    id: 'khalifa-bin-salman-port',
    latitude: 26.1886,
    location: 'Hidd / Muharraq',
    longitude: 50.7142,
    name: 'Khalifa Bin Salman Port',
    note: 'Public Bahraini commercial port with relevance to allied maritime logistics and sealift access.',
    region: 'Middle East',
    service: 'Navy',
    type: 'Partner access port',
  },
  {
    country: 'Greenland',
    id: 'nuuk-airport',
    latitude: 64.1906,
    location: 'Nuuk',
    longitude: -51.6764,
    name: 'Nuuk Airport',
    note: 'Public Greenland capital airport with growing Arctic logistics relevance for allied support and transit.',
    region: 'Arctic',
    service: 'Joint',
    type: 'Partner access airport',
  },
  {
    country: 'Greenland',
    id: 'kulusuk-airport',
    latitude: 65.5735,
    location: 'Kulusuk',
    longitude: -37.1234,
    name: 'Kulusuk Airport',
    note: 'Public east Greenland airport relevant to Arctic logistics and allied support routing.',
    region: 'Arctic',
    service: 'Joint',
    type: 'Partner access airport',
  },
  {
    country: 'Qatar',
    id: 'doha-port',
    latitude: 25.2937,
    location: 'Doha',
    longitude: 51.5456,
    name: 'Doha Port',
    note: 'Public Qatari port with periodic U.S. naval and maritime-security relevance alongside Hamad Port.',
    region: 'Middle East',
    service: 'Navy',
    type: 'Partner access port',
  },
  {
    country: 'United Arab Emirates',
    id: 'zayed-port',
    latitude: 24.5244,
    location: 'Abu Dhabi',
    longitude: 54.3799,
    name: 'Zayed Port',
    note: 'Public Abu Dhabi port of recurring relevance to partner maritime visits and Gulf logistics.',
    region: 'Middle East',
    service: 'Navy',
    type: 'Partner access port',
  },
  {
    country: 'United Arab Emirates',
    id: 'port-rashid',
    latitude: 25.2709,
    location: 'Dubai',
    longitude: 55.2658,
    name: 'Port Rashid',
    note: 'Public Dubai port with periodic allied maritime and logistics relevance in the Gulf.',
    region: 'Middle East',
    service: 'Navy',
    type: 'Partner access port',
  },
  {
    country: 'Philippines',
    id: 'basco-port',
    latitude: 20.4493,
    location: 'Basco, Batanes',
    longitude: 121.9684,
    name: 'Basco Port',
    note: 'Northern Philippines maritime node in Batanes with strategic relevance near the Luzon Strait.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Partner access port',
  },
  {
    country: 'Philippines',
    id: 'naval-base-rafael-ramos',
    latitude: 10.3009,
    location: 'Lapu-Lapu, Cebu',
    longitude: 123.9383,
    name: 'Naval Base Rafael Ramos',
    note: 'Philippine naval base and pier complex relevant to alliance maritime coordination in the central archipelago.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Partner naval base',
  },
  {
    country: 'Philippines',
    id: 'heracleo-alano-naval-base',
    latitude: 14.4943,
    location: 'Cavite City',
    longitude: 120.9087,
    name: 'Heracleo Alano Naval Base',
    note: 'Major Philippine Navy base in Manila Bay relevant to ship support, training, and alliance maritime coordination.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Partner naval base',
  },
  {
    country: 'Philippines',
    id: 'danilo-atienza-air-base',
    latitude: 14.4957,
    location: 'Sangley Point, Cavite',
    longitude: 120.9077,
    name: 'Danilo Atienza Air Base',
    note: 'Sangley Point air-and-maritime support location in Manila Bay with partner logistics relevance.',
    region: 'Indo-Pacific',
    service: 'Air Force',
    type: 'Partner access air base',
  },
  {
    country: 'Philippines',
    id: 'naval-station-felix-apolinario',
    latitude: 7.1538,
    location: 'Panacan, Davao',
    longitude: 125.6611,
    name: 'Naval Station Felix Apolinario',
    note: 'Southern Philippines naval station relevant to maritime coordination and sea-lane security in Mindanao waters.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Partner naval station',
  },
  {
    country: 'Philippines',
    id: 'naval-station-jose-andrada',
    latitude: 14.5607,
    location: 'Manila',
    longitude: 120.9851,
    name: 'Naval Station Jose Andrada',
    note: 'Philippine Navy headquarters complex in Manila with alliance coordination relevance.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Partner naval station',
  },
  {
    country: 'Philippines',
    id: 'port-of-batangas',
    latitude: 13.7607,
    location: 'Batangas',
    longitude: 121.046,
    name: 'Port of Batangas',
    note: 'Major Philippine sealift and logistics port with public relevance to allied maritime mobility.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Partner access port',
  },
  {
    country: 'Philippines',
    id: 'port-of-manila',
    latitude: 14.5852,
    location: 'Manila',
    longitude: 120.9727,
    name: 'Port of Manila',
    note: 'National gateway port of the Philippines with relevance to sealift, logistics, and alliance support planning.',
    region: 'Indo-Pacific',
    service: 'Navy',
    type: 'Partner access port',
  },
  {
    country: 'Federated States of Micronesia',
    id: 'yap-airfield',
    latitude: 9.498,
    location: 'Yap State',
    longitude: 138.082,
    name: 'Yap Airfield',
    note: 'Emerging Pacific access and posture site backed by public U.S.-FSM infrastructure agreements.',
    region: 'Indo-Pacific',
    service: 'Joint',
    type: 'Partner access airfield',
  },
]
