import type { SourceLink } from './types'

export type JudicialBiotechCaseGroupId =
  | 'genetics-ip'
  | 'biomedical-regulation'
  | 'tissue-consent'
  | 'ivf-embryos'
  | 'bioethics'

export interface JudicialBiotechCaseGroup {
  description: string
  id: JudicialBiotechCaseGroupId
  title: string
}

export interface JudicialBiotechCase {
  caseName: string
  court: string
  focus: string
  groupId: JudicialBiotechCaseGroupId
  holding: string
  id: string
  issue: string
  reviewLabel: 'Already SCOTUS' | 'Federal lower court' | 'State court'
  reviewPath: string
  reviewTone: 'federal' | 'scotus' | 'state'
  source: SourceLink
  sourceLinks?: SourceLink[]
  whyItMatters: string
  year: number
}

export const JUDICIAL_BIOTECH_CASE_GROUPS: JudicialBiotechCaseGroup[] = [
  {
    id: 'genetics-ip',
    title: 'Genetics, Patents & Research',
    description:
      'The core patent and research cases: engineered organisms, gene ownership, diagnostics, self-replicating tech, and drug-development safe harbors.',
  },
  {
    id: 'biomedical-regulation',
    title: 'Biomedical Regulation & Products',
    description:
      'Courts shaping FDA authority, vaccine and device liability, GMO regulation, and who gets to challenge science-heavy agency decisions.',
  },
  {
    id: 'tissue-consent',
    title: 'Tissue, Consent & Specimens',
    description:
      'Who controls excised cells, stored sperm, frozen embryos, and donated research specimens once biology turns into property or research material.',
  },
  {
    id: 'ivf-embryos',
    title: 'IVF, Embryos & Assisted Reproduction',
    description:
      'The leading embryo-disposition and surrogacy disputes: consent forms, divorce fights, clinic responsibility, and embryo status.',
  },
  {
    id: 'bioethics',
    title: 'Bioethics & Bodily Autonomy',
    description:
      'The harder ethical lane: end-of-life autonomy, assisted suicide, experimental drugs, embryo-research funding, and the infamous sterilization precedent.',
  },
]

const scotusReviewPath = 'Already the final U.S. Supreme Court ruling.'
const federalLowerReviewPath =
  'A federal lower-court decision. The Supreme Court could review it by certiorari, but review is discretionary.'
const stateHighCourtReviewPath =
  'Primarily a state-court ruling. The U.S. Supreme Court would usually step in only if a real federal question were presented.'

export const JUDICIAL_BIOTECH_CASES: JudicialBiotechCase[] = [
  {
    id: 'diamond-v-chakrabarty',
    groupId: 'genetics-ip',
    caseName: 'Diamond v. Chakrabarty',
    year: 1980,
    court: 'U.S. Supreme Court',
    focus: 'Patenting engineered life',
    issue: 'Could a genetically engineered bacterium count as patentable subject matter under federal patent law?',
    holding: 'Yes. A human-made microorganism could be patented.',
    whyItMatters:
      'This is the classic case on whether engineered living material can be owned through patents.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '1980',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/447/303/',
    },
  },
  {
    id: 'jem-ag-supply-v-pioneer',
    groupId: 'genetics-ip',
    caseName: 'J.E.M. Ag Supply, Inc. v. Pioneer Hi-Bred International, Inc.',
    year: 2001,
    court: 'U.S. Supreme Court',
    focus: 'Plant and seed patents',
    issue: 'Could newly developed plant breeds receive utility-patent protection?',
    holding: 'Yes. Utility patents remained available for plants and seeds.',
    whyItMatters:
      'A major ag-biotech case because it strengthened IP protection for proprietary seed technology.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '2001',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/534/124/',
    },
  },
  {
    id: 'merck-v-integra',
    groupId: 'genetics-ip',
    caseName: 'Merck KGaA v. Integra Lifesciences I, Ltd.',
    year: 2005,
    court: 'U.S. Supreme Court',
    focus: 'Drug-research safe harbor',
    issue: 'How broad is the federal safe harbor for preclinical experiments tied to drug development?',
    holding:
      'The federal safe harbor in 35 U.S.C. sec. 271(e)(1) was read broadly enough to cover preclinical experiments on patented compounds when there was a reasonable basis to think the work could produce information relevant to FDA review, even if a particular experiment or data set was not itself ultimately submitted.',
    whyItMatters:
      'It shapes how biotech and pharma firms test inventions before formal FDA submission.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '2005',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/545/193/',
    },
  },
  {
    id: 'eli-lilly-v-medtronic',
    groupId: 'genetics-ip',
    caseName: 'Eli Lilly & Co. v. Medtronic, Inc.',
    year: 1990,
    court: 'U.S. Supreme Court',
    focus: 'FDA patent safe harbor for device-related research',
    issue: 'Did the Hatch-Waxman research safe harbor reach medical-device work tied to federal regulatory approval, not just classic drug applications?',
    holding:
      'Yes. The Court held that 35 U.S.C. sec. 271(e)(1) is not limited to classic drug applications: it can also shield otherwise infringing uses of a patented invention when they are solely for developing and submitting information needed for FDCA premarket approval of a medical device, and more generally for other products regulated under that federal scheme.',
    whyItMatters:
      'It is the earlier Supreme Court safe-harbor building block behind later biotech and pharma research-exemption doctrine, including Merck.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '1990',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/496/661/',
    },
  },
  {
    id: 'mayo-v-prometheus',
    groupId: 'genetics-ip',
    caseName: 'Mayo Collaborative Services v. Prometheus Laboratories, Inc.',
    year: 2012,
    court: 'U.S. Supreme Court',
    focus: 'Diagnostics and laws of nature',
    issue: 'Could a diagnostic method based on metabolite levels and dosage correlations be patented?',
    holding: 'No. The claims effectively captured a law of nature plus routine steps.',
    whyItMatters:
      'This became one of the foundational limits on diagnostic and precision-medicine patent claims.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '2012',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/566/66/',
    },
  },
  {
    id: 'myriad-genetics',
    groupId: 'genetics-ip',
    caseName: 'Association for Molecular Pathology v. Myriad Genetics, Inc.',
    year: 2013,
    court: 'U.S. Supreme Court',
    focus: 'Human gene patents',
    issue: 'Can naturally occurring human DNA sequences be patented simply because they were isolated?',
    holding: 'Naturally occurring DNA was not patentable, while cDNA could be patent-eligible.',
    whyItMatters:
      'One of the biggest genomics rulings in U.S. law, especially for genetic testing and sequencing markets.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '2013',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/569/576/',
    },
  },
  {
    id: 'bowman-v-monsanto',
    groupId: 'genetics-ip',
    caseName: 'Bowman v. Monsanto Co.',
    year: 2013,
    court: 'U.S. Supreme Court',
    focus: 'Self-replicating seed technology',
    issue: 'Did patent exhaustion let a farmer replant patented seeds and reproduce later generations?',
    holding:
      'No. The Court held that patent exhaustion ends Monsanto’s control over the particular soybeans that were lawfully sold, but it does not let a buyer use those beans to make new patented seed through planting and harvesting without permission. In the Court’s view, Bowman was not just using the purchased article; he was creating additional copies of the patented invention.',
    whyItMatters:
      'A key case on self-replicating biotech products and how patent rights survive downstream use.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '2013',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/569/278/',
    },
  },
  {
    id: 'in-re-roslin-institute',
    groupId: 'genetics-ip',
    caseName: 'In re: Roslin Institute (Edinburgh)',
    year: 2014,
    court: 'U.S. Court of Appeals for the Federal Circuit',
    focus: 'Patentability of cloned animals',
    issue: 'Could a cloned mammal such as Dolly count as patent-eligible subject matter under federal patent law?',
    holding: 'No. The Federal Circuit said the claimed clones were not patent-eligible because they were not markedly different from naturally occurring animals.',
    whyItMatters:
      'A rare flagship cloning case about whether biotechnology can patent the cloned organism itself rather than only the method used to produce it.',
    reviewLabel: 'Federal lower court',
    reviewTone: 'federal',
    reviewPath: federalLowerReviewPath,
    source: {
      dateLabel: '2014',
      label: 'Federal Circuit case page',
      url: 'https://law.justia.com/cases/federal/appellate-courts/cafc/13-1407/13-1407-2014-05-08.html',
    },
  },
  {
    id: 'ariosa-v-sequenom',
    groupId: 'genetics-ip',
    caseName: 'Ariosa Diagnostics, Inc. v. Sequenom, Inc.',
    year: 2015,
    court: 'U.S. Court of Appeals for the Federal Circuit',
    focus: 'Prenatal diagnostics patent eligibility',
    issue: 'Could a groundbreaking method for detecting fetal DNA in maternal blood survive patent-eligibility review after Mayo?',
    holding: 'No. The Federal Circuit held the claims ineligible because they centered on a natural phenomenon plus conventional techniques.',
    whyItMatters:
      'One of the most controversial post-Mayo biotech cases because it hit noninvasive prenatal testing and diagnostic patent protection at the same time.',
    reviewLabel: 'Federal lower court',
    reviewTone: 'federal',
    reviewPath: federalLowerReviewPath,
    source: {
      dateLabel: '2015',
      label: 'Federal Circuit case page',
      url: 'https://law.justia.com/cases/federal/appellate-courts/cafc/14-1139/14-1139-2015-06-12.html',
    },
  },
  {
    id: 'amgen-v-sanofi',
    groupId: 'genetics-ip',
    caseName: 'Amgen Inc. v. Sanofi',
    year: 2023,
    court: 'U.S. Supreme Court',
    focus: 'Biologic drug patent enablement',
    issue: 'Could Amgen claim an entire genus of PCSK9-blocking antibodies without teaching skilled scientists how to make and use the full claimed class?',
    holding: 'No. The Court held that the patents failed the enablement requirement for the full claimed antibody genus.',
    whyItMatters:
      'A major modern biotech-patent case for antibody drugs, genus claims, and how much disclosure companies must give when seeking broad biologics monopolies.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '2023',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/598/21-757/',
    },
  },
  {
    id: 'monsanto-v-geertson',
    groupId: 'biomedical-regulation',
    caseName: 'Monsanto Co. v. Geertson Seed Farms',
    year: 2010,
    court: 'U.S. Supreme Court',
    focus: 'GMO deregulation and injunctions',
    issue: 'Could lower courts broadly block planting of genetically engineered alfalfa after NEPA defects?',
    holding: 'The Court said the nationwide injunction was too broad.',
    whyItMatters:
      'A major GMO-regulation case about how aggressively courts can halt biotech rollout after agency errors.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '2010',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/561/139/',
    },
  },
  {
    id: 'riegel-v-medtronic',
    groupId: 'biomedical-regulation',
    caseName: 'Riegel v. Medtronic, Inc.',
    year: 2008,
    court: 'U.S. Supreme Court',
    focus: 'Medical-device preemption',
    issue: 'Did FDA premarket approval preempt certain state-law claims over a medical device?',
    holding: 'Yes. Federal law preempted those state requirements in this setting.',
    whyItMatters:
      'A central case on the balance between FDA approval and state tort litigation over medical technology.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '2008',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/552/312/',
    },
  },
  {
    id: 'wyeth-v-levine',
    groupId: 'biomedical-regulation',
    caseName: 'Wyeth v. Levine',
    year: 2009,
    court: 'U.S. Supreme Court',
    focus: 'Drug-label liability',
    issue: 'Did FDA approval of a drug label automatically wipe out state failure-to-warn suits?',
    holding: 'No. FDA approval did not automatically preempt the claim here.',
    whyItMatters:
      'It remains one of the defining cases on drug regulation, warnings, and federal-state litigation overlap.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '2009',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/555/555/',
    },
  },
  {
    id: 'bruesewitz-v-wyeth',
    groupId: 'biomedical-regulation',
    caseName: 'Bruesewitz v. Wyeth LLC',
    year: 2011,
    court: 'U.S. Supreme Court',
    focus: 'Vaccine-law preemption',
    issue: 'Did the National Vaccine Injury Compensation Act bar certain design-defect claims against vaccine makers?',
    holding: 'Yes. The statute preempted that class of design-defect claims.',
    whyItMatters:
      'A major vaccine-liability case with long-term effects on product-litigation strategy and vaccine policy debates.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '2011',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/562/223/',
    },
  },
  {
    id: 'fda-v-alliance-for-hippocratic-medicine',
    groupId: 'biomedical-regulation',
    caseName: 'FDA v. Alliance for Hippocratic Medicine',
    year: 2024,
    court: 'U.S. Supreme Court',
    focus: 'Standing in science-regulation suits',
    issue: 'Could challengers unwind FDA actions on mifepristone on the record presented?',
    holding: 'No. The plaintiffs lacked Article III standing.',
    whyItMatters:
      'This is a modern case about who gets into court to attack federal biomedical-regulation decisions.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '2024',
      label: 'Supreme Court opinion (PDF)',
      url: 'https://www.supremecourt.gov/opinions/23pdf/23-235_n7ip.pdf',
    },
  },
  {
    id: 'medtronic-v-lohr',
    groupId: 'biomedical-regulation',
    caseName: 'Medtronic, Inc. v. Lohr',
    year: 1996,
    court: 'U.S. Supreme Court',
    focus: 'Device preemption before full PMA review',
    issue: 'Did federal medical-device law broadly wipe out state tort claims over a pacemaker that reached market through the 510(k) pathway?',
    holding: 'Not broadly. The Court allowed core claims to proceed and read preemption narrowly in that setting.',
    whyItMatters:
      'A foundational medical-device case on FDA clearance, state tort law, and the later preemption battles that dominate device litigation.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '1996',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/518/470/',
    },
  },
  {
    id: 'buckman-v-plaintiffs-legal-committee',
    groupId: 'biomedical-regulation',
    caseName: "Buckman Co. v. Plaintiffs' Legal Committee",
    year: 2001,
    court: 'U.S. Supreme Court',
    focus: 'Fraud-on-the-FDA claims',
    issue: 'Could plaintiffs use state tort law to argue that a device reached market only because the defendant misled the FDA?',
    holding: 'No. The Court held those fraud-on-the-FDA claims were impliedly preempted by federal law.',
    whyItMatters:
      'A landmark case on who polices deception in the FDA process and how far private plaintiffs can weaponize agency-approval disputes.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '2001',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/531/341/',
    },
  },
  {
    id: 'pliva-v-mensing',
    groupId: 'biomedical-regulation',
    caseName: 'PLIVA, Inc. v. Mensing',
    year: 2011,
    court: 'U.S. Supreme Court',
    focus: 'Generic-drug warning preemption',
    issue: 'Could injured patients bring state failure-to-warn claims against generic manufacturers when federal law required the generic label to match the brand-name label?',
    holding: 'No. The claims were preempted because the generic manufacturers could not unilaterally change their labels.',
    whyItMatters:
      'One of the most important modern drug-preemption cases and hugely consequential for generic-drug litigation and patient recovery.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '2011',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/564/604/',
    },
  },
  {
    id: 'mutual-pharmaceutical-v-bartlett',
    groupId: 'biomedical-regulation',
    caseName: 'Mutual Pharmaceutical Co. v. Bartlett',
    year: 2013,
    court: 'U.S. Supreme Court',
    focus: 'Generic-drug design-defect preemption',
    issue: "Could a plaintiff recover on a state design-defect theory when federal law barred the generic maker from changing the drug's composition or label?",
    holding: 'No. The Court held the design-defect claim was preempted in that setting.',
    whyItMatters:
      'It extended the modern generic-preemption line and closed another major path for product-liability suits over generic drugs.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '2013',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/570/472/',
    },
  },
  {
    id: 'moore-v-regents',
    groupId: 'tissue-consent',
    caseName: 'Moore v. Regents of the University of California',
    year: 1990,
    court: 'California Supreme Court',
    focus: 'Ownership of excised cells',
    issue: 'Did a patient keep property rights in cells removed from his body and later commercialized?',
    holding: 'The court rejected a conversion claim over the cells but allowed informed-consent-related theories.',
    whyItMatters:
      'One of the most famous cases on tissue ownership, commercialization, and physician disclosure duties.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '1990',
      label: 'California Supreme Court case page',
      url: 'https://law.justia.com/cases/california/supreme-court/3d/51/120.html',
    },
  },
  {
    id: 'greenberg-v-miami-childrens-hospital',
    groupId: 'tissue-consent',
    caseName: "Greenberg v. Miami Children's Hospital Research Institute",
    year: 2002,
    court: 'U.S. District Court for the Northern District of Illinois',
    focus: 'Donor rights, gene patents, and disease research',
    issue: 'What legal rights did families and advocacy groups have after they supplied tissue, data, and funding for Canavan disease research and later learned the resulting gene work had been patented and tightly licensed?',
    holding: 'In the Illinois opinion most often cited from this dispute, the court transferred the case on jurisdiction and venue grounds rather than resolving the full merits in Illinois.',
    whyItMatters:
      'Even with that procedural posture, it became one of the signature judicial disputes about donor expectations, genetic research, and the commercialization of disease-related discoveries.',
    reviewLabel: 'Federal lower court',
    reviewTone: 'federal',
    reviewPath: federalLowerReviewPath,
    source: {
      dateLabel: '2002',
      label: 'Federal case page',
      url: 'https://law.justia.com/cases/federal/district-courts/FSupp2/208/918/2563184/',
    },
  },
  {
    id: 'havasupai-tribe-v-arizona-board-of-regents',
    groupId: 'tissue-consent',
    caseName: 'Havasupai Tribe v. Arizona Board of Regents',
    year: 2008,
    court: 'Arizona Court of Appeals',
    focus: 'Secondary use of biospecimens beyond consent',
    issue: 'Could tribal members pursue claims after blood samples given for diabetes research were allegedly used for unrelated genetic, migration, and other studies without proper consent?',
    holding: 'The appellate court held that the notices of claim were sufficient and allowed the litigation to go forward rather than ending it on the state notice-of-claim issue.',
    whyItMatters:
      'One of the most important U.S. biospecimen-consent disputes because it centers on secondary use, group dignity, and research involving indigenous communities.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '2008',
      label: 'Arizona appellate case page',
      url: 'https://law.justia.com/cases/arizona/court-of-appeals-division-one-published/2008/cv070454.html',
    },
  },
  {
    id: 'unruh-haxton-v-regents',
    groupId: 'tissue-consent',
    caseName: 'Unruh-Haxton v. Regents of the University of California',
    year: 2008,
    court: 'California Court of Appeal',
    focus: 'Misuse of eggs and pre-embryos',
    issue: 'Could patients sue over allegations that a fertility clinic stole and misused their eggs and pre-embryos?',
    holding: 'The court allowed key claims to go forward and rejected the idea that media coverage alone put plaintiffs on notice.',
    whyItMatters:
      'A major fertility-clinic abuse case about consent, misuse of reproductive material, and delayed discovery of wrongdoing.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '2008',
      label: 'California appellate case page',
      url: 'https://caselaw.findlaw.com/court/ca-court-of-appeal/1317196.html',
    },
  },
  {
    id: 'washington-university-v-catalona',
    groupId: 'tissue-consent',
    caseName: 'Washington University v. Catalona',
    year: 2007,
    court: 'U.S. Court of Appeals for the Eighth Circuit',
    focus: 'Research specimen control',
    issue: 'Who controlled donated biological specimens held in a university research repository?',
    holding: 'The court sided with the university rather than treating donors as retaining full ownership control.',
    whyItMatters:
      'It is a major biospecimen-governance case for biobanks, consent language, and research institutions.',
    reviewLabel: 'Federal lower court',
    reviewTone: 'federal',
    reviewPath: federalLowerReviewPath,
    source: {
      dateLabel: '2007',
      label: 'Case text',
      textFragment: 'Washington University v. Catalona',
      url: 'https://opencasebook.org/documents/1435/',
    },
  },
  {
    id: 'colavito-v-new-york-organ-donor-network',
    groupId: 'tissue-consent',
    caseName: 'Colavito v. New York Organ Donor Network, Inc.',
    year: 2006,
    court: 'New York Court of Appeals',
    focus: 'Directed organ-donation rights',
    issue: 'What legal rights arise when a specifically directed organ donation cannot be completed as intended?',
    holding: 'The court declined to recognize the broad property-style recovery the plaintiff sought on the facts presented.',
    whyItMatters:
      'A leading body-material case because it tests how far private rights and conversion theories extend in organ donation.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '2006',
      label: 'New York Court of Appeals case page',
      url: 'https://law.justia.com/cases/new-york/court-of-appeals/2006/2006-09320.html',
    },
  },
  {
    id: 'york-v-jones',
    groupId: 'tissue-consent',
    caseName: 'York v. Jones',
    year: 1989,
    court: 'U.S. District Court for the Eastern District of Virginia',
    focus: 'Frozen embryo transfer rights',
    issue: 'Could a couple compel an IVF clinic to transfer their cryopreserved embryo to another clinic?',
    holding: 'The court allowed the contract-based claim to proceed.',
    whyItMatters:
      'An early and influential reproductive-technology case about clinic control over cryopreserved embryos.',
    reviewLabel: 'Federal lower court',
    reviewTone: 'federal',
    reviewPath: federalLowerReviewPath,
    source: {
      dateLabel: '1989',
      label: 'Federal case page',
      url: 'https://law.justia.com/cases/federal/district-courts/FSupp/717/421/1584239/',
    },
  },
  {
    id: 'hecht-v-superior-court',
    groupId: 'tissue-consent',
    caseName: 'Hecht v. Superior Court',
    year: 1993,
    court: 'California Court of Appeal',
    focus: 'Stored sperm after death',
    issue: 'What legal interests attach to cryopreserved sperm after the donor dies?',
    holding: 'The court recognized a legally protected interest sufficient to let the dispute proceed.',
    whyItMatters:
      'A widely cited posthumous-reproduction case about stored gametes, intent, and estate control.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '1993',
      label: 'California appellate case page',
      url: 'https://law.justia.com/cases/california/court-of-appeal/4th/16/836.html',
    },
  },
  {
    id: 'davis-v-davis',
    groupId: 'ivf-embryos',
    caseName: 'Davis v. Davis',
    year: 1992,
    court: 'Tennessee Supreme Court',
    focus: 'Embryo disposition after divorce',
    issue: 'How should frozen embryos be treated when former spouses disagree about their future use?',
    holding: 'The court generally favored the right to avoid procreation absent a prior controlling agreement.',
    whyItMatters:
      'This is one of the foundational embryo-disposition cases in American reproductive law.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '1992',
      label: 'Case text',
      textFragment: 'Davis v. Davis',
      url: 'https://opencasebook.org/casebooks/8829-reproductive-rights-health-and-justice-law-and-policy/as-printable-html/9/',
    },
  },
  {
    id: 'kass-v-kass',
    groupId: 'ivf-embryos',
    caseName: 'Kass v. Kass',
    year: 1998,
    court: 'New York Court of Appeals',
    focus: 'IVF consent contracts',
    issue: 'Should an IVF consent form control what happens to frozen pre-zygotes after the couple separates?',
    holding: "Yes. The court enforced the parties' previous written agreement.",
    whyItMatters:
      'It is the leading example of courts enforcing reproductive-technology consent documents as contracts.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '1998',
      label: 'New York Court of Appeals case page',
      url: 'https://law.justia.com/cases/new-york/court-of-appeals/1998/91-n-y-2d-554-0.html',
    },
  },
  {
    id: 'km-v-eg',
    groupId: 'ivf-embryos',
    caseName: 'K.M. v. E.G.',
    year: 2005,
    court: 'California Supreme Court',
    focus: 'Egg donation, parentage, and intended family structure',
    issue: 'Was a woman who provided ova to her domestic partner merely a donor, or could she also be a legal parent of the resulting children?',
    holding: 'The court held that she was a parent too, not merely an ova donor, because the children were meant to be raised in the couple\'s joint home.',
    whyItMatters:
      'It is a major assisted-reproduction parentage case because it rejects an overly simple donor analogy in a real family-setting.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '2005',
      label: 'California Supreme Court case page',
      url: 'https://law.justia.com/cases/california/supreme-court/2005/s125643.html',
    },
  },
  {
    id: 'johnson-v-calvert',
    groupId: 'ivf-embryos',
    caseName: 'Johnson v. Calvert',
    year: 1993,
    court: 'California Supreme Court',
    focus: 'Gestational surrogacy and intended parenthood',
    issue: 'When genetic and gestational motherhood split, who is the legal mother under a surrogacy arrangement?',
    holding: 'The court recognized the intended genetic mother, not the gestational surrogate, as the legal mother.',
    whyItMatters:
      'One of the most famous assisted-reproduction cases because it shaped the intent-based approach to surrogacy and parentage.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '1993',
      label: 'California Supreme Court case page',
      url: 'https://scocal.stanford.edu/opinion/johnson-v-calvert-31446',
    },
  },
  {
    id: 'az-v-bz',
    groupId: 'ivf-embryos',
    caseName: 'A.Z. v. B.Z.',
    year: 2000,
    court: 'Massachusetts Supreme Judicial Court',
    focus: 'Limits on embryo-disposition contracts',
    issue: "Could a prior clinic form be enforced to compel one former spouse to become a parent against that person's will?",
    holding: 'No. The court refused to enforce the arrangement in a way that would force parenthood.',
    whyItMatters:
      'A major counterpoint to the strong contract approach because it treats compelled parenthood as a public-policy problem.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '2000',
      label: 'Massachusetts Supreme Judicial Court case page',
      url: 'https://law.justia.com/cases/massachusetts/supreme-court/volumes/431/431mass150.html',
    },
  },
  {
    id: 'jb-v-mb',
    groupId: 'ivf-embryos',
    caseName: 'J.B. v. M.B.',
    year: 2001,
    court: 'Supreme Court of New Jersey',
    focus: 'Revocable consent and the right not to procreate',
    issue: 'Could a divorced husband force preserved preembryos to be donated or used after the wife changed her mind and wanted them destroyed?',
    holding: 'No. The New Jersey Supreme Court held that the wife could not be forced into unwanted genetic parenthood and adopted a rule giving special weight to the right not to procreate.',
    whyItMatters:
      'One of the core embryo-disposition precedents because it refines the contract-versus-balancing debate and strongly protects revocable consent.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '2001',
      label: 'Embryo Project case summary',
      url: 'https://embryo.asu.edu/pages/j-b-v-m-b-2001',
    },
  },
  {
    id: 'in-re-marriage-of-witten',
    groupId: 'ivf-embryos',
    caseName: 'In re Marriage of Witten',
    year: 2003,
    court: 'Iowa Supreme Court',
    focus: 'Contemporaneous mutual-consent approach',
    issue: 'How should frozen embryos be handled when ex-spouses disagree and no one can use or release them without the other\'s consent?',
    holding: 'The court adopted a contemporaneous mutual-consent approach that effectively kept the embryos in storage unless both parties agreed on a disposition.',
    whyItMatters:
      'This is one of the classic counter-models in embryo case law, often contrasted with both contract-first and balancing approaches.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '2003',
      label: 'Case text',
      textFragment: 'In re Marriage of Witten',
      url: 'https://case-law.vlex.com/vid/in-re-marriage-of-892165220',
    },
  },
  {
    id: 'dahl-and-angle',
    groupId: 'ivf-embryos',
    caseName: 'Dahl and Angle',
    year: 2008,
    court: 'Oregon Court of Appeals',
    focus: 'Enforcing IVF consent forms after divorce',
    issue: 'Should an Oregon divorce court enforce the parties\' signed IVF storage agreement directing what would happen to frozen embryos when they later disagreed?',
    holding: 'Yes. The Oregon Court of Appeals upheld the agreement and affirmed the judgment ordering destruction of the embryos under its terms.',
    whyItMatters:
      'A major embryo-disposition case because it strongly reinforces the contract-first approach and is often cited alongside Davis, Kass, and Witten.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '2008',
      label: 'Oregon appellate case page',
      url: 'https://law.justia.com/cases/oregon/court-of-appeals/2008/a133697.html',
    },
  },
  {
    id: 'litowitz-v-litowitz',
    groupId: 'ivf-embryos',
    caseName: 'Litowitz v. Litowitz',
    year: 2002,
    court: 'Washington Supreme Court',
    focus: 'Frozen-embryo contract limits',
    issue: 'How should a court resolve a dispute over cryopreserved embryos after a couple separates?',
    holding: "The court resolved the dispute by applying the parties' agreement and the clinic timeline.",
    whyItMatters:
      'It is one of the major state high-court embryo cases after Davis and Kass.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '2002',
      label: 'Washington Supreme Court case page',
      url: 'https://law.justia.com/cases/washington/supreme-court/2002/70413-9-4.html',
    },
  },
  {
    id: 'baby-m',
    groupId: 'ivf-embryos',
    caseName: 'In the Matter of Baby M',
    year: 1988,
    court: 'New Jersey Supreme Court',
    focus: 'Surrogacy and parental rights',
    issue: 'How should the law treat a commercial surrogacy arrangement and the resulting custody dispute?',
    holding: "The court invalidated the surrogacy contract while resolving custody under the child's best interests.",
    whyItMatters:
      'A landmark assisted-reproduction case that still shapes how courts and legislatures think about surrogacy.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '1988',
      label: 'New Jersey Supreme Court case page',
      url: 'https://law.justia.com/cases/new-jersey/supreme-court/1988/109-n-j-396-1.html',
    },
  },
  {
    id: 'lepage-v-center-for-reproductive-medicine',
    groupId: 'ivf-embryos',
    caseName: 'LePage v. Center for Reproductive Medicine, P.C.',
    year: 2024,
    court: 'Alabama Supreme Court',
    focus: 'Embryo status and wrongful death',
    issue: "Could frozen embryos count as children under Alabama's wrongful-death statute?",
    holding: 'The court allowed the wrongful-death claims to proceed on that theory.',
    whyItMatters:
      'One of the most consequential recent IVF cases because it directly disrupted fertility-clinic practice.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '2024',
      label: 'Alabama Supreme Court case page',
      url: 'https://law.justia.com/cases/alabama/supreme-court/2024/sc-2022-0579.html',
    },
  },
  {
    id: 'roman-v-roman',
    groupId: 'ivf-embryos',
    caseName: 'Roman v. Roman',
    year: 2006,
    court: 'Texas Court of Appeals',
    focus: 'Enforcing embryo agreements in divorce',
    issue: 'Should a divorce court follow the couple\'s prior embryo-disposition agreement or reassign the frozen embryos as part of the property division?',
    holding: 'The appellate court held the agreement should control and that the embryos should be discarded as the parties had specified for divorce.',
    whyItMatters:
      'It is a leading contract-first embryo case and one of the clearest examples of a court refusing to rewrite the parties\' prior IVF agreement.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '2006',
      label: 'Texas appellate case page',
      url: 'https://law.justia.com/cases/texas/first-court-of-appeals/2006/82705.html',
    },
  },
  {
    id: 'finkelstein-v-finkelstein',
    groupId: 'ivf-embryos',
    caseName: 'Finkelstein v. Finkelstein',
    year: 2018,
    court: 'New York Appellate Division, First Department',
    focus: 'Revocation of consent and disposal',
    issue: 'Could one spouse revoke consent under the clinic agreement and prevent the other spouse from using the remaining frozen embryo?',
    holding: 'The appellate court ruled that the revocation language in the consent agreement controlled and awarded the embryo for disposal under clinic procedures.',
    whyItMatters:
      'It is an important modern embryo-disposition case because it turns on the exact wording of clinic consent and revocation provisions.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '2018',
      label: 'New York appellate case page',
      url: 'https://law.justia.com/cases/new-york/appellate-division-first-department/2018/5820n-309125-13.html',
    },
  },
  {
    id: 'reber-v-reiss',
    groupId: 'ivf-embryos',
    caseName: 'Reber v. Reiss',
    year: 2012,
    court: 'Pennsylvania Superior Court',
    focus: 'Cancer-related fertility preservation and balancing approach',
    issue: 'Could a wife who created frozen pre-embryos before cancer treatment receive control of them over her ex-husband\'s objection when they were likely her only realistic path to biological motherhood?',
    holding: 'Yes. The Pennsylvania Superior Court used a balancing approach and awarded the pre-embryos to the wife on the specific facts presented.',
    whyItMatters:
      'This is one of the most-cited embryo-disposition cases in the country because it made the balancing approach concrete in a cancer-preservation setting before later cases like Rooks and Pieper.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '2012',
      label: 'Family-law summary',
      url: 'https://todaysfamilylawyer.co.uk/frozen-embryos-the-risks-and-the-rewards/',
    },
  },
  {
    id: 'szafranski-v-dunston',
    groupId: 'ivf-embryos',
    caseName: 'Szafranski v. Dunston',
    year: 2013,
    court: 'Illinois Appellate Court',
    focus: 'Cancer-preservation embryos and oral agreement',
    issue: 'Could a woman use frozen pre-embryos created before cancer treatment over the objection of the former partner who provided sperm?',
    holding: 'The court treated the dispute through a contract-centered framework and remanded for that approach to be applied.',
    whyItMatters:
      'A nationally cited embryo case because fertility preservation in the face of cancer treatment made the equities especially stark.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '2013',
      label: 'Illinois appellate case page',
      url: 'https://law.justia.com/cases/illinois/court-of-appeals-first-appellate-district/2013/1-12-2975.html',
    },
  },
  {
    id: 'in-re-marriage-of-rooks',
    groupId: 'ivf-embryos',
    caseName: 'In re Marriage of Rooks',
    year: 2018,
    court: 'Colorado Supreme Court',
    focus: 'Balancing test for embryo disputes',
    issue: 'How should courts resolve embryo disputes when no controlling agreement clearly answers the divorce scenario?',
    holding: 'The court adopted a structured balancing framework rather than a pure contemporaneous-consent rule.',
    whyItMatters:
      'One of the most influential modern embryo cases because later courts repeatedly borrow its balancing factors.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '2018',
      label: 'Colorado Supreme Court case page',
      url: 'https://law.justia.com/cases/colorado/supreme-court/2018/16sc906.html',
    },
  },
  {
    id: 'bilbao-v-goodwin',
    groupId: 'ivf-embryos',
    caseName: 'Bilbao v. Goodwin',
    year: 2019,
    court: 'Connecticut Supreme Court',
    focus: 'Embryo-disposition framework synthesis',
    issue: 'What approach should govern the disposition of frozen pre-embryos when relationships end and agreements are disputed?',
    holding: 'The court endorsed a contract-first approach while mapping the major competing frameworks in other states.',
    whyItMatters:
      'It is one of the clearest state supreme court opinions comparing the national embryo-case landscape in one place.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '2019',
      label: 'Connecticut Supreme Court case page',
      url: 'https://law.justia.com/cases/connecticut/supreme-court/2019/sc20078.html',
    },
  },
  {
    id: 'terrell-v-torres',
    groupId: 'ivf-embryos',
    caseName: 'Terrell v. Torres',
    year: 2019,
    court: 'Arizona Court of Appeals',
    focus: 'Embryo disputes after cancer-related preservation',
    issue: 'How should Arizona courts handle frozen-embryo disputes when a party argues the embryos are the last realistic path to genetic parenthood?',
    holding: 'The court rejected automatic enforcement and sent the dispute back under a more nuanced legal framework.',
    whyItMatters:
      'A strong modern case because it sits at the intersection of cancer-related fertility preservation and post-relationship conflict.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '2019',
      label: 'Arizona appellate case page',
      url: 'https://law.justia.com/cases/arizona/court-of-appeals-division-one-published/2019/1-ca-cv-17-0617.html',
    },
  },
  {
    id: 'mcqueen-v-gadberry',
    groupId: 'ivf-embryos',
    caseName: 'McQueen v. Gadberry',
    year: 2016,
    court: 'Missouri Court of Appeals',
    focus: 'Embryos as marital property of special character',
    issue: 'In a divorce, should frozen pre-embryos be treated as children, ordinary property, or something in between?',
    holding: 'The court treated them as marital property of a special character and refused to award them for use over the ex-husband\'s objection.',
    whyItMatters:
      'A widely cited embryo-disposition case because it rejected simple personhood and simple property analogies at the same time.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '2016',
      label: 'Missouri appellate case page',
      url: 'https://case-law.vlex.com/vid/mcqueen-v-gadberry-no-899779248',
    },
  },
  {
    id: 'david-freed-v-elizabeth-freed',
    groupId: 'ivf-embryos',
    caseName: 'David Freed v. Elizabeth Freed',
    year: 2024,
    court: 'Indiana Court of Appeals',
    focus: 'Modern balancing approach in embryo disputes',
    issue: 'Did awarding a remaining frozen pre-embryo to the ex-wife over the ex-husband\'s objection violate his constitutional interest in avoiding procreation?',
    holding: 'The appellate court affirmed the award to the wife after concluding that the trial court used the appropriate balancing framework.',
    whyItMatters:
      'It is a very recent embryo-disposition case that explicitly walks through the national case-law split and chooses a modern balancing approach.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '2024',
      label: 'Indiana appellate case page',
      url: 'https://law.justia.com/cases/indiana/court-of-appeals/2024/23a-dc-00129.html',
    },
  },
  {
    id: 'el-v-as',
    groupId: 'ivf-embryos',
    caseName: 'E.L. v. A.S.',
    year: 2025,
    court: 'Supreme Court of New York County',
    focus: 'Recent contract-first embryo ruling',
    issue: 'Should the court enforce the parties\' declarations of intent for cryopreserved embryos after divorce, or instead order destruction?',
    holding: 'The court awarded the cryopreserved embryos for implantation under the parties\' written declarations and denied the request to destroy them.',
    whyItMatters:
      'It is a very recent embryo-disposition decision that synthesizes Kass, Finkelstein, A.Z., J.B., and Davis while emphasizing the force of clear written IVF directives.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '2025',
      label: 'New York case page',
      url: 'https://law.justia.com/cases/new-york/other-courts/2025/2025-ny-slip-op-25261.html',
    },
  },
  {
    id: 'buzzanca',
    groupId: 'ivf-embryos',
    caseName: 'In re Marriage of Buzzanca',
    year: 1998,
    court: 'California Court of Appeal',
    focus: 'Intended parenthood without genetic ties',
    issue: 'When a child is born through assisted reproduction using donor egg, donor sperm, and a surrogate, can the intending couple still be the legal parents even without a genetic link?',
    holding: 'Yes. The appellate court held that the intending husband and wife were the lawful parents.',
    whyItMatters:
      'A major assisted-reproduction case because it pushes parentage doctrine beyond simple genetics or gestation and toward intentional creation of a family.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '1998',
      label: 'California appellate case page',
      url: 'https://law.justia.com/cases/california/court-of-appeal/4th/61/1410.html',
    },
  },
  {
    id: 'jocelyn-p-v-joshua-p',
    groupId: 'ivf-embryos',
    caseName: 'Jocelyn P. v. Joshua P.',
    year: 2021,
    court: 'Maryland Appellate Court',
    focus: 'Modern framework for frozen pre-embryo disputes',
    issue: 'How should Maryland courts decide the fate of a frozen pre-embryo when divorcing spouses disagree about whether it should be used or discarded?',
    holding: 'The court treated the dispute as one of first impression, directed trial courts to look first to the parties\' prior agreement, and then use a balancing framework if no controlling agreement resolves the issue.',
    whyItMatters:
      'A significant modern embryo-dispute case because it lays out a detailed framework in a large state that previously lacked binding appellate guidance.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '2021',
      label: 'Maryland appellate case page',
      url: 'https://law.justia.com/cases/maryland/court-of-special-appeals/2021/2125-19.html',
    },
  },
  {
    id: 'pm-v-tb',
    groupId: 'ivf-embryos',
    caseName: 'P.M. v. T.B.',
    year: 2018,
    court: 'Iowa Supreme Court',
    focus: 'Gestational surrogacy contract enforcement',
    issue: 'Could Iowa courts enforce a gestational-surrogacy agreement in favor of the intended biological father against the surrogate and her husband?',
    holding: 'Yes. The Iowa Supreme Court enforced the gestational-surrogacy contract, recognized the intended biological father\'s parental status, and terminated the surrogate couple\'s presumptive parental rights.',
    whyItMatters:
      'A strong assisted-reproduction precedent because it squarely treats gestational-surrogacy contracts as enforceable absent contrary state law.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '2018',
      label: 'Iowa Supreme Court case page',
      url: 'https://law.justia.com/cases/iowa/supreme-court/2018/17-0376.html',
    },
  },
  {
    id: 'markiewicz-v-markiewicz',
    groupId: 'ivf-embryos',
    caseName: 'Sarah Marie Markiewicz v. David Randal Markiewicz',
    year: 2022,
    court: 'Michigan Court of Appeals',
    focus: 'Frozen embryo as special marital property in divorce',
    issue: 'How should a Michigan divorce court treat a cryogenically preserved embryo when the parties dispute whether it should be awarded to one spouse for possible implantation?',
    holding: 'The appellate court remanded for a more complete property analysis while emphasizing that a frozen embryo is not just ordinary marital property and may warrant special treatment.',
    whyItMatters:
      'A notable modern embryo-disposition case because Michigan had little direct precedent and the court explicitly recognized the embryo\'s unique status in divorce litigation.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '2022',
      label: 'Michigan appellate case page',
      url: 'https://law.justia.com/cases/michigan/court-of-appeals-unpublished/2022/355774-1.html',
    },
  },
  {
    id: 'olsen',
    groupId: 'ivf-embryos',
    caseName: 'In re Marriage of Olsen',
    year: 2022,
    court: 'Colorado Court of Appeals',
    focus: 'Donation-versus-nonprocreation dispute after breakup',
    issue: 'Could a spouse who wanted to donate disputed pre-embryos prevail over the other spouse\'s objection that donation would still make him a genetic parent against his will?',
    holding: 'No. Applying Colorado\'s Rooks framework, the court held that this was not one of the rare cases in which donation should overcome the other party\'s interest in avoiding procreation.',
    whyItMatters:
      'A strong follow-on to Rooks because it shows how the balancing framework works when one side seeks donation rather than implantation.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '2022',
      label: 'Colorado appellate case page',
      url: 'https://law.justia.com/cases/colorado/court-of-appeals/2022/20ca1881.html',
    },
  },
  {
    id: 'smith-v-smith-ga',
    groupId: 'ivf-embryos',
    caseName: 'Jonathan Smith v. Lauri Smith',
    year: 2023,
    court: 'Court of Appeals of Georgia',
    focus: 'Contract-controlled embryo disposition in divorce',
    issue: 'Did the trial court err by awarding the stored embryo to the wife for possible implantation instead of enforcing the couple\'s prior IVF agreement calling for donation if they later could not agree?',
    holding: 'Yes. The Georgia Court of Appeals held that the agreement controlled and that the embryo should be handled according to the parties\' prior donation choice rather than a fresh equitable balancing by the divorce court.',
    whyItMatters:
      'A major modern state appellate case because it treats embryo-disposition contracts as enforceable even in emotionally difficult divorce disputes.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '2023',
      label: 'Georgia appellate case page',
      url: 'https://law.justia.com/cases/georgia/court-of-appeals/2023/a23a0896.html',
    },
  },
  {
    id: 'pieper-v-carlson',
    groupId: 'ivf-embryos',
    caseName: 'Dawn Pieper v. Jacob Thomas Carlson',
    year: 2024,
    court: 'Minnesota Court of Appeals',
    focus: 'Balancing interests in preserved pre-embryos after relationship breakdown',
    issue: 'Should a former partner receive control of preserved pre-embryos to pursue biological parenthood when the other former partner opposes becoming a genetic parent?',
    holding: 'No. The court affirmed the denial of relief after a balancing analysis that favored the objecting partner\'s interest in avoiding genetic parenthood on the specific record presented.',
    whyItMatters:
      'A useful modern case because it shows how lower courts are borrowing from Rooks, Reber, and Davis even in states that still lack a definitive homegrown framework.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '2024',
      label: 'Minnesota appellate case page',
      url: 'https://law.justia.com/cases/minnesota/court-of-appeals/2024/a23-0806.html',
    },
  },
  {
    id: 'canterbury-v-spence',
    groupId: 'bioethics',
    caseName: 'Canterbury v. Spence',
    year: 1972,
    court: 'U.S. Court of Appeals for the D.C. Circuit',
    focus: 'Modern informed-consent doctrine',
    issue: 'Did a physician have a duty to disclose material risks of surgery even if many doctors would not ordinarily volunteer that information?',
    holding: 'Yes. The D.C. Circuit made patient-centered informed consent a legal duty rather than leaving disclosure almost entirely to medical custom.',
    whyItMatters:
      'This is one of the most influential informed-consent cases in American law and a cornerstone of modern medical autonomy doctrine.',
    reviewLabel: 'Federal lower court',
    reviewTone: 'federal',
    reviewPath: federalLowerReviewPath,
    source: {
      dateLabel: '1972',
      label: 'D.C. Circuit case page',
      url: 'https://openjurist.org/464/f2d/772/canterbury-v-spence',
    },
  },
  {
    id: 'mink-v-university-of-chicago',
    groupId: 'bioethics',
    caseName: 'Mink v. University of Chicago',
    year: 1978,
    court: 'U.S. District Court for the Northern District of Illinois',
    focus: 'Nonconsensual medical experimentation',
    issue: 'Did women who were given DES during prenatal care without their knowledge or consent state a viable claim arising from secret participation in a medical experiment?',
    holding: 'Yes. The district court held that the allegations could support a battery claim and allowed the core claim to proceed.',
    whyItMatters:
      'One of the clearest judicial treatments of nonconsensual human experimentation in U.S. medical research litigation.',
    reviewLabel: 'Federal lower court',
    reviewTone: 'federal',
    reviewPath: federalLowerReviewPath,
    source: {
      dateLabel: '1978',
      label: 'Federal case page',
      url: 'https://law.justia.com/cases/federal/district-courts/FSupp/460/713/2093161/',
    },
  },
  {
    id: 'united-states-v-stanley',
    groupId: 'bioethics',
    caseName: 'United States v. Stanley',
    year: 1987,
    court: 'U.S. Supreme Court',
    focus: 'Secret LSD testing on human subjects',
    issue: 'Could a serviceman secretly dosed with LSD during military experimentation pursue a constitutional damages remedy against federal officials?',
    holding: 'No. The Court barred the Bivens route in the military setting, even though the case arose from covert human experimentation.',
    whyItMatters:
      'A major human-subjects case because the facts involve undisclosed military drug experiments, and the ruling shows how little damages access can remain even in shocking experimentation cases.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '1987',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/483/669/',
    },
  },
  {
    id: 'barrett-v-united-states',
    groupId: 'bioethics',
    caseName: 'Barrett v. United States',
    year: 1986,
    court: 'U.S. District Court for the Southern District of New York',
    focus: 'Secret mescaline experimentation and cover-up',
    issue: 'Could claims proceed arising from allegations that Harold Blauer was injected with Army-supplied mescaline derivatives in a psychiatric setting without informed consent, followed by a long concealment of the experiment?',
    holding: 'The district court allowed the claims to proceed against the United States under the Federal Tort Claims Act framework then before it.',
    whyItMatters:
      'A major Cold War human-experimentation case because it deals with nonconsensual chemical testing, death, and an alleged government cover-up.',
    reviewLabel: 'Federal lower court',
    reviewTone: 'federal',
    reviewPath: federalLowerReviewPath,
    source: {
      dateLabel: '1986',
      label: 'Federal case page',
      url: 'https://law.justia.com/cases/federal/district-courts/FSupp/646/1345/1749884/',
    },
  },
  {
    id: 'glover-v-eastern-nebraska-community-office-of-retardation',
    groupId: 'bioethics',
    caseName: 'Glover v. Eastern Nebraska Community Office of Retardation',
    year: 1988,
    court: 'U.S. District Court for the District of Nebraska',
    focus: 'Mandatory HIV testing of employees',
    issue: 'Could a state human-services agency require broad mandatory HIV testing of workers whose jobs involved contact with clients, based on a claimed risk of transmission?',
    holding: 'No. The district court held the policy unconstitutional on the record before it because the testing burden outweighed the asserted need.',
    whyItMatters:
      'A high-signal HIV-testing case because it treats broad compulsory testing as an unjustified intrusion where the underlying transmission risk was extremely low.',
    reviewLabel: 'Federal lower court',
    reviewTone: 'federal',
    reviewPath: federalLowerReviewPath,
    source: {
      dateLabel: '1988',
      label: 'Federal case page',
      url: 'https://law.justia.com/cases/federal/district-courts/FSupp/686/243/1362568/',
    },
  },
  {
    id: 'plowman-v-us-dept-of-army',
    groupId: 'bioethics',
    caseName: 'Plowman v. U.S. Department of Army',
    year: 1988,
    court: 'U.S. District Court for the Eastern District of Virginia',
    focus: 'Nonconsensual HIV testing on an existing blood sample',
    issue: 'Did a civilian Army employee have viable constitutional claims after military doctors added an HIV test to blood already drawn for other diagnostic purposes without telling him in advance?',
    holding: 'The court ultimately granted summary judgment to the defendant commander, but the case squarely confronted the legality of nonconsensual HIV testing from an already-collected sample.',
    whyItMatters:
      'A significant covert-testing case because it sharply frames the difference between consent to a blood draw and consent to additional hidden testing on that sample.',
    reviewLabel: 'Federal lower court',
    reviewTone: 'federal',
    reviewPath: federalLowerReviewPath,
    source: {
      dateLabel: '1988',
      label: 'Federal case page',
      url: 'https://law.justia.com/cases/federal/district-courts/FSupp/698/627/2356978/',
    },
  },
  {
    id: 'stadt-v-university-of-rochester',
    groupId: 'bioethics',
    caseName: 'Stadt v. University of Rochester',
    year: 1996,
    court: 'U.S. District Court for the Western District of New York',
    focus: 'Secret plutonium injection and long-term covert study',
    issue: 'Could claims proceed based on allegations that a patient was injected with plutonium while being told she was receiving treatment for scleroderma, and then studied for years without being told the truth?',
    holding: 'Yes. The district court refused to dismiss the core federal claim at the pleading stage.',
    whyItMatters:
      'One of the starkest U.S. covert-experiment cases because it links Cold War radiation research, false pretenses, and years of undisclosed follow-up testing.',
    reviewLabel: 'Federal lower court',
    reviewTone: 'federal',
    reviewPath: federalLowerReviewPath,
    source: {
      dateLabel: '1996',
      label: 'Federal case page',
      url: 'https://law.justia.com/cases/federal/district-courts/FSupp/921/1023/1988360/',
    },
  },
  {
    id: 'norman-bloodsaw-v-lawrence-berkeley-laboratory',
    groupId: 'bioethics',
    caseName: 'Norman-Bloodsaw v. Lawrence Berkeley Laboratory',
    year: 1998,
    court: 'U.S. Court of Appeals for the Ninth Circuit',
    focus: 'Unauthorized pregnancy, syphilis, and sickle-cell testing',
    issue: 'Did employees state viable privacy and constitutional claims after alleging that blood and urine samples were secretly tested for pregnancy, syphilis, and sickle-cell trait without valid notice or consent?',
    holding: 'Yes in substantial part. The Ninth Circuit recognized a powerful privacy interest against secret testing for sensitive medical conditions and allowed core claims to proceed.',
    whyItMatters:
      'A flagship unauthorized-testing case because it squarely treats covert medical screening as a serious invasion of privacy, especially where the tests carry stigma or genetic implications.',
    reviewLabel: 'Federal lower court',
    reviewTone: 'federal',
    reviewPath: federalLowerReviewPath,
    source: {
      dateLabel: '1998',
      label: 'Ninth Circuit case page',
      url: 'https://law.justia.com/cases/federal/appellate-courts/F3/135/1260/507541/',
    },
  },
  {
    id: 'doe-v-high-tech-institute',
    groupId: 'bioethics',
    caseName: 'Doe v. High-Tech Institute, Inc.',
    year: 1998,
    court: 'Colorado Court of Appeals',
    focus: 'Unauthorized HIV testing and disclosure',
    issue: 'Did a student state a privacy claim after consenting to a rubella test but then having his blood secretly tested for HIV and the result disclosed?',
    holding: 'Yes. The Colorado Court of Appeals held that unauthorized HIV testing under those alleged circumstances could amount to an offensive intrusion on privacy.',
    whyItMatters:
      'A strong unauthorized-testing case because it treats limited consent to one medical test as not automatically authorizing hidden testing for something far more sensitive.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '1998',
      label: 'Colorado appellate case page',
      url: 'https://law.justia.com/cases/colorado/court-of-appeals/1998/97ca0385-0.html',
    },
  },
  {
    id: 'roe-v-wade',
    groupId: 'bioethics',
    caseName: 'Roe v. Wade',
    year: 1973,
    court: 'U.S. Supreme Court',
    focus: 'Abortion rights and reproductive autonomy',
    issue: 'Did the Constitution protect a decision to terminate pregnancy before fetal viability?',
    holding: 'Yes. The Court held that the Due Process Clause protected that choice under the framework it adopted at the time.',
    whyItMatters:
      'One of the most important reproductive-autonomy and medical-choice decisions in modern American law.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '1973',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/410/113/',
    },
  },
  {
    id: 'in-re-quinlan',
    groupId: 'bioethics',
    caseName: 'In Re Quinlan',
    year: 1976,
    court: 'Supreme Court of New Jersey',
    focus: 'Withdrawal of life support',
    issue: 'Could a guardian authorize removal of a respirator from a patient in a persistent vegetative state?',
    holding: 'Yes. The New Jersey Supreme Court recognized a privacy-based framework and allowed the guardian and physicians to proceed.',
    whyItMatters:
      'One of the most famous end-of-life cases in American law and a direct ancestor to later right-to-refuse-treatment doctrine.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '1976',
      label: 'New Jersey Supreme Court case page',
      url: 'https://law.justia.com/cases/new-jersey/supreme-court/1976/70-n-j-10-0.html',
    },
  },
  {
    id: 'saikewicz',
    groupId: 'bioethics',
    caseName: 'Superintendent of Belchertown State Sch. v. Saikewicz',
    year: 1977,
    court: 'Supreme Judicial Court of Massachusetts',
    focus: 'Refusing burdensome treatment for an incompetent patient',
    issue: 'Could chemotherapy be withheld from a profoundly disabled patient with leukemia through a substituted-judgment approach?',
    holding: 'Yes. The Massachusetts high court allowed treatment to be withheld using substituted judgment.',
    whyItMatters:
      'A canonical bioethics case on informed consent, substituted judgment, and the limits of life-prolonging treatment.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '1977',
      label: 'Massachusetts high-court case page',
      url: 'https://law.justia.com/cases/massachusetts/supreme-court/1977/373-mass-728-2.html',
    },
  },
  {
    id: 'whalen-v-roe',
    groupId: 'bioethics',
    caseName: 'Whalen v. Roe',
    year: 1977,
    court: 'U.S. Supreme Court',
    focus: 'Health-data privacy and prescription monitoring',
    issue: 'Could New York require identifying information to be reported for certain prescription drugs without violating constitutional privacy interests?',
    holding: 'Yes. The Court upheld the reporting system on the record before it.',
    whyItMatters:
      'An early landmark on medical-data privacy, prescription surveillance, and how public-health regulation intersects with personal information.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '1977',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/429/589/',
    },
  },
  {
    id: 'cincinnati-radiation-litigation',
    groupId: 'bioethics',
    caseName: 'In Re Cincinnati Radiation Litigation',
    year: 1995,
    court: 'U.S. District Court for the Southern District of Ohio',
    focus: 'Concealed radiation experiments',
    issue: 'Could plaintiffs pursue constitutional and related claims based on allegations that the true purpose and dangers of human radiation experiments had been concealed from them for decades?',
    holding: 'At the pleading stage, the district court held that the plaintiffs had sufficiently alleged constitutional injuries tied to concealment of the experiments and their risks.',
    whyItMatters:
      'One of the most important modern judicial opinions arising from Cold War human experimentation and the concealment of research risks.',
    reviewLabel: 'Federal lower court',
    reviewTone: 'federal',
    reviewPath: federalLowerReviewPath,
    source: {
      dateLabel: '1995',
      label: 'Federal case page',
      url: 'https://law.justia.com/cases/federal/district-courts/FSupp/874/796/1478171/',
    },
  },
  {
    id: 'matter-of-conroy',
    groupId: 'bioethics',
    caseName: 'Matter of Conroy',
    year: 1985,
    court: 'Supreme Court of New Jersey',
    focus: 'Withdrawing artificial nutrition and hydration',
    issue: 'What standards and procedures should govern decisions to withhold or withdraw life-sustaining treatment from an incompetent nursing-home patient?',
    holding: 'The court created a detailed state-law framework for when life-sustaining treatment, including artificial feeding, could be withdrawn.',
    whyItMatters:
      'A landmark right-to-die case because it translated Quinlan into a more detailed doctrine for incompetent patients and feeding-tube disputes.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '1985',
      label: 'New Jersey Supreme Court case page',
      url: 'https://law.justia.com/cases/new-jersey/supreme-court/1985/98-n-j-321-0.html',
    },
  },
  {
    id: 'bouvia-v-superior-court',
    groupId: 'bioethics',
    caseName: 'Bouvia v. Superior Court (Glenchur)',
    year: 1986,
    court: 'California Court of Appeal',
    focus: 'Competent patient refusing forced feeding',
    issue: 'Could a competent, severely disabled patient demand removal of a feeding tube and refuse life-prolonging nutrition against hospital wishes?',
    holding: 'Yes. The court held that a competent patient could refuse that treatment even if death would follow.',
    whyItMatters:
      'A major bodily-autonomy case because it strongly framed refusal of treatment as the patient\'s decision, not the hospital\'s.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '1986',
      label: 'California appellate case page',
      url: 'https://law.justia.com/cases/california/court-of-appeal/3d/179/1127.html',
    },
  },
  {
    id: 'matter-of-peter',
    groupId: 'bioethics',
    caseName: 'Matter of Peter by Johanning',
    year: 1987,
    court: 'Supreme Court of New Jersey',
    focus: 'Withdrawal of tube feeding in persistent vegetative state',
    issue: 'Under what standards could a guardian seek withdrawal of a nasogastric tube from a patient in a persistent vegetative state who was not expected to die in the immediate future?',
    holding: 'The New Jersey Supreme Court allowed withdrawal under a state-law framework built around the patient\'s likely wishes and surrogate decisionmaking.',
    whyItMatters:
      'An important right-to-die decision because it pushed end-of-life doctrine beyond imminent-death cases and addressed long-term tube feeding directly.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '1987',
      label: 'New Jersey Supreme Court case page',
      url: 'https://law.justia.com/cases/new-jersey/supreme-court/1987/108-n-j-365-0.html',
    },
  },
  {
    id: 'addington-v-texas',
    groupId: 'bioethics',
    caseName: 'Addington v. Texas',
    year: 1979,
    court: 'U.S. Supreme Court',
    focus: 'Standard of proof for involuntary civil commitment',
    issue: 'What burden of proof does due process require before the state can involuntarily commit a person for mental-health treatment?',
    holding: 'The Court required at least clear-and-convincing evidence rather than a mere preponderance standard.',
    whyItMatters:
      'A major mental-health law case on bodily liberty, psychiatric confinement, and the procedural safeguards surrounding involuntary treatment.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '1979',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/441/418/',
    },
  },
  {
    id: 'parham-v-jr',
    groupId: 'bioethics',
    caseName: 'Parham v. J.R.',
    year: 1979,
    court: 'U.S. Supreme Court',
    focus: 'Commitment of minors for psychiatric treatment',
    issue: 'How much process is constitutionally required before a child is admitted to a state mental hospital at the request of a parent or guardian?',
    holding: 'The Court rejected a full adversarial hearing requirement but required an independent medical-style inquiry into whether commitment was appropriate.',
    whyItMatters:
      'A key case on child psychiatry, parental authority, and the state procedures needed before major mental-health confinement decisions.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '1979',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/442/584/',
    },
  },
  {
    id: 'cruzan-v-director-missouri',
    groupId: 'bioethics',
    caseName: 'Cruzan v. Director, Missouri Department of Health',
    year: 1990,
    court: 'U.S. Supreme Court',
    focus: 'Right to refuse treatment',
    issue: 'What process may a state require before life-sustaining treatment is withdrawn from an incompetent patient?',
    holding: "The Court allowed Missouri to require clear and convincing evidence of the patient's wishes.",
    whyItMatters:
      'This is a foundational end-of-life autonomy case in modern American bioethics.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '1990',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/497/261/',
    },
  },
  {
    id: 'degrella-v-elston',
    groupId: 'bioethics',
    caseName: 'DeGrella by and Through Parrent v. Elston',
    year: 1993,
    court: 'Supreme Court of Kentucky',
    focus: 'Withdrawal of feeding tube and artificial nutrition',
    issue: 'Could life-sustaining artificial nutrition and hydration be withdrawn from a woman in a persistent vegetative state under Kentucky law?',
    holding: 'Yes. The Kentucky Supreme Court treated tube feeding as a medical intervention that could be withdrawn under the governing right-to-refuse-treatment principles.',
    whyItMatters:
      'A significant right-to-die case because it squarely treats artificial nutrition and hydration as medical treatment rather than something categorically different.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '1993',
      label: 'Kentucky Supreme Court case page',
      url: 'https://law.justia.com/cases/kentucky/supreme-court/1993/92-sc-756-tg-1.html',
    },
  },
  {
    id: 'thor-v-superior-court',
    groupId: 'bioethics',
    caseName: 'Thor v. Superior Court (Andrews)',
    year: 1993,
    court: 'Supreme Court of California',
    focus: 'Prisoner refusing life-sustaining care',
    issue: 'Could a competent prisoner refuse life-sustaining feeding, medication, and related treatment even if death might follow?',
    holding: 'Yes. The California Supreme Court held that a competent adult retained the right to refuse treatment, and prison officials generally could not override that choice absent special institutional concerns.',
    whyItMatters:
      'A strong autonomy case because it extends refusal-of-treatment principles into the prison setting instead of confining them to ordinary hospital patients.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '1993',
      label: 'California Supreme Court case page',
      url: 'https://law.justia.com/cases/california/supreme-court/4th/5/725.html',
    },
  },
  {
    id: 'jacobson-v-massachusetts',
    groupId: 'bioethics',
    caseName: 'Jacobson v. Massachusetts',
    year: 1905,
    court: 'U.S. Supreme Court',
    focus: 'Compulsory vaccination and public health power',
    issue: 'Could a state require vaccination during a smallpox outbreak as a matter of public-health law?',
    holding: 'Yes. The Court upheld compulsory vaccination as a valid exercise of the state police power, subject to limits against arbitrary or oppressive use.',
    whyItMatters:
      'It is the classic U.S. vaccination and public-health case, and it still shapes debates over state power in biomedical emergencies.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '1905',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/197/11/',
    },
  },
  {
    id: 'washington-v-harper',
    groupId: 'bioethics',
    caseName: 'Washington v. Harper',
    year: 1990,
    court: 'U.S. Supreme Court',
    focus: 'Forced antipsychotic medication in prison',
    issue: 'What process and substantive limits apply when the state wants to medicate a mentally ill prison inmate against his will?',
    holding: 'The Court held that due process allows forced antipsychotic medication of a seriously mentally ill inmate who is dangerous to self or others when the treatment is in the inmate\'s medical interest.',
    whyItMatters:
      'This is one of the core cases on bodily autonomy, psychiatry, state custody, and forced medical treatment.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '1990',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/494/210/',
    },
  },
  {
    id: 'riggins-v-nevada',
    groupId: 'bioethics',
    caseName: 'Riggins v. Nevada',
    year: 1992,
    court: 'U.S. Supreme Court',
    focus: 'Forced medication during trial',
    issue: 'Could the state continue antipsychotic medication during a murder trial without adequately showing need and reasonable alternatives?',
    holding: 'No. The forced medication violated due process because the state did not make the required showing of need and less intrusive alternatives.',
    whyItMatters:
      'It is a major follow-on to Harper because it focuses on trial fairness, courtroom demeanor, and the effect of psychiatric drugs on criminal proceedings.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '1992',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/504/127/',
    },
  },
  {
    id: 'planned-parenthood-v-casey',
    groupId: 'bioethics',
    caseName: 'Planned Parenthood of Southeastern Pennsylvania v. Casey',
    year: 1992,
    court: 'U.S. Supreme Court',
    focus: 'Reproductive autonomy and abortion regulation',
    issue: 'Should Roe be reaffirmed, and what constitutional test should govern abortion regulations before viability?',
    holding: 'The Court reaffirmed the core abortion right at the time but replaced Roe\'s framework with the undue-burden standard and upheld most of the challenged provisions.',
    whyItMatters:
      'This became the controlling abortion-regulation framework for decades and reshaped the constitutional law of reproductive decisionmaking.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '1992',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/505/833/',
    },
  },
  {
    id: 'in-re-ac',
    groupId: 'bioethics',
    caseName: 'In Re A.C.',
    year: 1990,
    court: 'District of Columbia Court of Appeals',
    focus: 'Forced cesarean and maternal autonomy',
    issue: 'Under what circumstances, if any, can a court order major surgery on a pregnant patient for the sake of the fetus?',
    holding: 'The D.C. Court of Appeals condemned the handling of the case and emphasized that competent patients generally control their own medical decisions.',
    whyItMatters:
      'A leading maternal-fetal conflict case in American bioethics and hospital decisionmaking.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '1990',
      label: 'D.C. Court of Appeals case page',
      url: 'https://law.justia.com/cases/district-of-columbia/court-of-appeals/1990/87-609-4.html',
    },
  },
  {
    id: 'sell-v-united-states',
    groupId: 'bioethics',
    caseName: 'Sell v. United States',
    year: 2003,
    court: 'U.S. Supreme Court',
    focus: 'Forced medication to restore trial competence',
    issue: 'Could the government forcibly medicate a mentally ill criminal defendant to make him competent to stand trial?',
    holding: 'Sometimes, but only under a demanding multi-part constitutional standard.',
    whyItMatters:
      'A core case on psychiatric medication, bodily autonomy, and the state interest in adjudicating criminal charges.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '2003',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/539/166/',
    },
  },
  {
    id: 'grimes-v-kennedy-krieger-institute',
    groupId: 'bioethics',
    caseName: 'Grimes v. Kennedy Krieger Institute, Inc.',
    year: 2001,
    court: 'Court of Appeals of Maryland',
    focus: 'Nontherapeutic research on children',
    issue: 'Could parents validly consent to children participating in lead-abatement research that exposed them to risk without offering direct therapeutic benefit?',
    holding: 'The Maryland high court let negligence claims proceed and sharply questioned whether parents could authorize that kind of risky nontherapeutic research.',
    whyItMatters:
      'One of the clearest American judicial opinions on human-subject research ethics, vulnerable children, and the limits of parental consent in experimentation.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '2001',
      label: 'AMA ethics analysis',
      url: 'https://journalofethics.ama-assn.org/article/grimes-v-kennedy-krieger-institute-nontherapeutic-research-children/2003-11',
    },
  },
  {
    id: 'wright-v-fred-hutchinson',
    groupId: 'bioethics',
    caseName: 'Wright v. Fred Hutchinson Cancer Research Center',
    year: 2002,
    court: 'U.S. District Court for the Western District of Washington',
    focus: 'Experimental cancer protocols and research consent',
    issue: 'Did participants in an experimental cancer-treatment protocol state federal and research-ethics-based claims based on alleged failures to disclose key risks, conflicts, and alternatives?',
    holding: 'The district court rejected the standalone Nuremberg-Code and constitutional dignity theories on the pleadings, while sharply distinguishing undisclosed experimentation from cases involving patients who knew they were entering an experimental protocol.',
    whyItMatters:
      'A widely cited research-ethics opinion because it maps the boundary between outright secret experimentation and allegedly inadequate informed consent in therapeutic research.',
    reviewLabel: 'Federal lower court',
    reviewTone: 'federal',
    reviewPath: federalLowerReviewPath,
    source: {
      dateLabel: '2002',
      label: 'Federal case page',
      url: 'https://law.justia.com/cases/federal/district-courts/FSupp2/269/1286/2528162/',
    },
  },
  {
    id: 'looney-v-moore',
    groupId: 'bioethics',
    caseName: 'Looney v. Moore',
    year: 2015,
    court: 'U.S. District Court for the Northern District of Alabama',
    focus: 'SUPPORT trial and research informed consent',
    issue: 'Could families recover for injuries allegedly tied to the SUPPORT oxygen-randomization study on extremely premature infants, based on arguments that the research design and consent process exposed infants to undisclosed comparative risks?',
    holding: 'No. The district court granted summary judgment to the defendants under the state-law theory presented.',
    whyItMatters:
      'It is one of the highest-profile modern research-ethics cases in the United States because it sits at the center of the SUPPORT-trial debate over randomization, standard-of-care research, and what informed consent must disclose.',
    reviewLabel: 'Federal lower court',
    reviewTone: 'federal',
    reviewPath: federalLowerReviewPath,
    source: {
      dateLabel: '2015',
      label: 'Petrie-Flom case analysis',
      url: 'https://petrieflom.law.harvard.edu/2015/11/03/understanding-lost-chances-to-recover-and-looney-v-moore/',
    },
  },
  {
    id: 'heinrich-v-sweet',
    groupId: 'bioethics',
    caseName: 'Heinrich ex rel. Heinrich v. Sweet',
    year: 1999,
    court: 'U.S. District Court for the District of Massachusetts',
    focus: 'False-pretenses experimentation versus ordinary informed consent',
    issue: 'Could a medical-treatment suit proceed on the theory that the patient was used as an experimental subject under false pretenses rather than merely receiving inadequate informed-consent disclosures?',
    holding: 'The district court drew a sharp distinction between ordinary informed-consent claims and allegations of nontherapeutic experimentation under false pretenses, allowing the case to proceed on that more serious theory.',
    whyItMatters:
      'It is one of the clearest U.S. opinions distinguishing routine disclosure failures from actual human experimentation carried out without real consent.',
    reviewLabel: 'Federal lower court',
    reviewTone: 'federal',
    reviewPath: federalLowerReviewPath,
    source: {
      dateLabel: '1999',
      label: 'Federal case page',
      url: 'https://law.justia.com/cases/federal/district-courts/FSupp2/62/282/2410538/',
    },
  },
  {
    id: 'abdullahi-v-pfizer',
    groupId: 'bioethics',
    caseName: 'Abdullahi v. Pfizer, Inc.',
    year: 2009,
    court: 'U.S. Court of Appeals for the Second Circuit',
    focus: 'Nonconsensual drug testing on children',
    issue: 'Could plaintiffs pursue claims arising from allegations that children in Nigeria were subjected to an experimental antibiotic trial without valid consent?',
    holding: 'The Second Circuit held that the alleged prohibition on nonconsensual human medical experimentation was sufficiently definite to be enforceable through the Alien Tort Statute and sent the case back for further proceedings.',
    whyItMatters:
      'A major modern human-subjects case because it treats nonconsensual medical experimentation as a serious, actionable norm in transnational litigation.',
    reviewLabel: 'Federal lower court',
    reviewTone: 'federal',
    reviewPath: federalLowerReviewPath,
    source: {
      dateLabel: '2009',
      label: 'Second Circuit case page',
      url: 'https://law.justia.com/cases/federal/appellate-courts/ca2/05-4863/05-4863-cv_opn-2011-03-27.html',
    },
  },
  {
    id: 'kanuszewski-v-michigan-dhhs',
    groupId: 'bioethics',
    caseName: 'Kanuszewski v. Michigan Department of Health & Human Services',
    year: 2019,
    court: 'U.S. Court of Appeals for the Sixth Circuit',
    focus: 'Newborn blood screening, storage, and later research use without informed consent',
    issue: 'Could parents and children press constitutional claims arising from the state\'s collection, retention, storage, and later research or third-party use of newborn blood spots allegedly without valid informed consent?',
    holding: 'In part yes. The Sixth Circuit revived significant constitutional claims and sent the case back for further proceedings.',
    whyItMatters:
      'A major modern biospecimen case because it connects newborn screening, biobank retention, later research use, and informed-consent limits in a large state program.',
    reviewLabel: 'Federal lower court',
    reviewTone: 'federal',
    reviewPath: federalLowerReviewPath,
    source: {
      dateLabel: '2019',
      label: 'Sixth Circuit case page',
      url: 'https://law.justia.com/cases/federal/appellate-courts/ca6/18-1896/18-1896-2019-06-10.html',
    },
  },
  {
    id: 'skinner-v-oklahoma',
    groupId: 'bioethics',
    caseName: 'Skinner v. Oklahoma ex rel. Williamson',
    year: 1942,
    court: 'U.S. Supreme Court',
    focus: 'Punitive sterilization and eugenics',
    issue: 'Could Oklahoma forcibly sterilize certain repeat offenders under its habitual-criminal sterilization law?',
    holding: 'No. The Court struck the law down under the Equal Protection Clause.',
    whyItMatters:
      'This is the canonical anti-eugenic sterilization case and a core reproductive-autonomy precedent in American constitutional law.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '1942',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/316/535/',
    },
  },
  {
    id: 'washington-v-glucksberg',
    groupId: 'bioethics',
    caseName: 'Washington v. Glucksberg',
    year: 1997,
    court: 'U.S. Supreme Court',
    focus: 'Physician-assisted suicide',
    issue: 'Did the federal Constitution create a fundamental right to physician-assisted suicide?',
    holding: 'No. The Court rejected that claimed fundamental right.',
    whyItMatters:
      'A defining constitutional bioethics case on assisted dying and bodily autonomy.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '1997',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/521/702/',
    },
  },
  {
    id: 'vacco-v-quill',
    groupId: 'bioethics',
    caseName: 'Vacco v. Quill',
    year: 1997,
    court: 'U.S. Supreme Court',
    focus: 'Assisted suicide and equal protection',
    issue: "Did New York's ban on assisted suicide violate equal protection because patients could refuse life-sustaining treatment?",
    holding: 'No. The Court upheld the ban and rejected the equal-protection challenge.',
    whyItMatters:
      'Together with Glucksberg, this is one of the defining modern Supreme Court cases on assisted dying and end-of-life law.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '1997',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/521/793/',
    },
  },
  {
    id: 'buck-v-bell',
    groupId: 'bioethics',
    caseName: 'Buck v. Bell',
    year: 1927,
    court: 'U.S. Supreme Court',
    focus: 'Forced sterilization and eugenics',
    issue: 'Could a state forcibly sterilize a woman under a eugenic statute?',
    holding: 'The Court upheld the sterilization law.',
    whyItMatters:
      'This is one of the darkest and most infamous bioethics cases in American judicial history.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '1927',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/274/200/',
    },
  },
  {
    id: 'abigail-alliance-v-von-eschenbach',
    groupId: 'bioethics',
    caseName: 'Abigail Alliance for Better Access to Developmental Drugs v. von Eschenbach',
    year: 2007,
    court: 'U.S. Court of Appeals for the D.C. Circuit',
    focus: 'Access to experimental drugs',
    issue: 'Did terminally ill patients have a constitutional right to access investigational drugs after Phase I testing?',
    holding: 'No. The en banc court rejected that claimed constitutional right.',
    whyItMatters:
      'A major case on compassionate use, drug development, and the constitutional limits of experimental access claims.',
    reviewLabel: 'Federal lower court',
    reviewTone: 'federal',
    reviewPath: federalLowerReviewPath,
    source: {
      dateLabel: '2007',
      label: 'D.C. Circuit case page',
      url: 'https://law.justia.com/cases/federal/appellate-courts/cadc/04-5350/04-5350c-2011-03-24.html',
    },
  },
  {
    id: 'in-re-fiori',
    groupId: 'bioethics',
    caseName: 'In Re Fiori',
    year: 1996,
    court: 'Supreme Court of Pennsylvania',
    focus: 'Decision standards for withdrawing life-sustaining treatment',
    issue: 'Who may decide to withdraw life-sustaining treatment from a patient in a persistent vegetative state who left no clear prior directions, and under what standard?',
    holding: 'The Pennsylvania Supreme Court set out the governing procedures and standards for surrogate decisionmaking in that setting.',
    whyItMatters:
      'A leading state high-court case on how right-to-die rules operate when the patient\'s wishes are not clearly documented in advance.',
    reviewLabel: 'State court',
    reviewTone: 'state',
    reviewPath: stateHighCourtReviewPath,
    source: {
      dateLabel: '1996',
      label: 'Pennsylvania Supreme Court case page',
      url: 'https://law.justia.com/cases/pennsylvania/supreme-court/1996/543-pa-592-1.html',
    },
  },
  {
    id: 'united-states-v-rutherford',
    groupId: 'bioethics',
    caseName: 'United States v. Rutherford',
    year: 1979,
    court: 'U.S. Supreme Court',
    focus: 'Terminal patients and unapproved drugs',
    issue: 'Did terminally ill cancer patients have a statutory right to obtain Laetrile outside the normal FDA approval framework?',
    holding: 'No. The Court refused to create that exception to federal drug law.',
    whyItMatters:
      'An early landmark on experimental treatment access and the tension between desperation medicine and FDA gatekeeping.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '1979',
      label: 'Supreme Court case page',
      url: 'https://supreme.justia.com/cases/federal/us/442/544/',
    },
  },
  {
    id: 'dobbs-v-jackson',
    groupId: 'bioethics',
    caseName: "Dobbs v. Jackson Women's Health Organization",
    year: 2022,
    court: 'U.S. Supreme Court',
    focus: 'Abortion rights reversal',
    issue: 'Did the Constitution continue to protect a pre-viability abortion right?',
    holding: 'No. The Court overruled Roe and Casey and returned abortion regulation largely to the political process.',
    whyItMatters:
      'One of the most consequential modern bioethics and reproductive-autonomy decisions because it overturned nearly fifty years of Supreme Court abortion-rights doctrine.',
    reviewLabel: 'Already SCOTUS',
    reviewTone: 'scotus',
    reviewPath: scotusReviewPath,
    source: {
      dateLabel: '2022',
      label: 'Supreme Court opinion (PDF)',
      url: 'https://www.supremecourt.gov/opinions/21pdf/19-1392_6j37.pdf',
    },
  },
  {
    id: 'sherley-v-sebelius',
    groupId: 'bioethics',
    caseName: 'Sherley v. Sebelius',
    year: 2012,
    court: 'U.S. Court of Appeals for the D.C. Circuit',
    focus: 'Embryonic stem-cell funding',
    issue: 'Did federal funding rules for embryonic stem-cell research violate the Dickey-Wicker Amendment?',
    holding: 'The court let the NIH embryonic stem-cell funding policy stay in effect, so federal funding for that research continued.',
    whyItMatters:
      'A leading case on how courts treat federal stem-cell-research policy and statutory limits on embryo destruction.',
    reviewLabel: 'Federal lower court',
    reviewTone: 'federal',
    reviewPath: federalLowerReviewPath,
    source: {
      dateLabel: '2012',
      label: 'D.C. Circuit case page',
      url: 'https://law.justia.com/cases/federal/appellate-courts/cadc/11-5241/11-5241-2012-08-24.html',
    },
  },
]
